export declare const ActionType: {
  // --- CORE SYSTEM & PLAY ACTIONS ---
  readonly PLAY_HERO: "PLAY_HERO";
  readonly PLAY_EVIL_CHARACTER: "PLAY_EVIL_CHARACTER";
  readonly PLAY_GOOD_ENHANCEMENT: "PLAY_GOOD_ENHANCEMENT";
  readonly PLAY_EVIL_ENHANCEMENT: "PLAY_EVIL_ENHANCEMENT";
  readonly PLAY_LOST_SOUL: "PLAY_LOST_SOUL";
  readonly PLAY_FORTRESS: "PLAY_FORTRESS";
  readonly PLAY_SITE: "PLAY_SITE";
  
  // --- OFFICIAL EFFECTS FROM THE REG TABLE OF CONTENTS ---
  readonly ACTIVATE_ABILITY: "ACTIVATE_ABILITY";
  readonly ACTIVATE_ARTIFACT: "ACTIVATE_ARTIFACT";
  readonly ADD_TO_BATTLE: "ADD_TO_BATTLE";
  readonly BAND: "BAND";
  readonly BANISH: "BANISH";
  readonly BEGIN_NEW_PHASE: "BEGIN_NEW_PHASE";
  readonly BOUNCE: "BOUNCE";
  readonly CAPTURE: "CAPTURE";
  readonly CHANGE_HAND_SIZE: "CHANGE_HAND_SIZE";
  readonly CHOOSE_OPPONENT: "CHOOSE_OPPONENT";
  readonly CONVERT: "CONVERT";
  readonly COPY: "COPY";
  readonly CREATE_TOKEN: "CREATE_TOKEN";
  readonly DECREASE: "DECREASE";
  readonly DISCARD: "DISCARD";
  readonly DISEASE: "DISEASE";
  readonly DRAW: "DRAW";
  readonly END_BATTLE: "END_BATTLE";
  readonly EQUIP: "EQUIP";
  readonly EXCHANGE: "EXCHANGE";
  readonly FIRST_STRIKE: "FIRST_STRIKE";
  readonly GAIN: "GAIN";
  readonly GIVE: "GIVE";
  readonly HEAL: "HEAL";
  readonly HOLD: "HOLD";
  readonly IGNORE: "IGNORE";
  readonly IMMUNE: "IMMUNE";
  readonly INCREASE: "INCREASE";
  readonly INTERRUPT: "INTERRUPT";
  readonly LOOK: "LOOK";
  readonly NEGATE: "NEGATE";
  readonly PARALYZE: "PARALYZE";
  readonly PLACE: "PLACE";
  readonly PLAY_AN_ENHANCEMENT: "PLAY_AN_ENHANCEMENT";
  readonly POISON: "POISON";
  readonly PRESENT: "PRESENT";
  readonly PREVENT: "PREVENT";
  readonly PROTECT: "PROTECT";
  readonly REDIRECT: "REDIRECT";
  readonly RELEASE: "RELEASE";
  readonly REMOVE_FROM_GAME: "REMOVE_FROM_GAME";
  readonly REPEAT: "REPEAT";
  readonly RESCUE: "RESCUE";
  readonly RESERVE: "RESERVE";
  readonly RESTRICT: "RESTRICT";
  readonly RESURRECT: "RESURRECT";
  readonly RETURN_TO_HAND: "RETURN_TO_HAND";
  readonly REVEAL: "REVEAL";
  readonly SEARCH: "SEARCH";
  readonly SET_ASIDE: "SET_ASIDE";
  readonly SHUFFLE: "SHUFFLE";
  readonly SIDE_BATTLE: "SIDE_BATTLE";
  readonly SITE_ACCESS: "SITE_ACCESS";
  readonly TAKE: "TAKE";
  readonly TAUNT: "TAUNT";
  readonly TOPDECK: "TOPDECK";
  readonly TOSS: "TOSS";
  readonly TRANSFER: "TRANSFER";
  readonly UNDERDECK: "UNDERDECK";
  readonly USE_OTHER_ENHANCEMENTS: "USE_OTHER_ENHANCEMENTS";
  readonly WITHDRAW: "WITHDRAW";

  // --- SPECIAL MECHANICS FROM RELEVANT RULES TEXT ---
  readonly ACTIVATE_STAR_ABILITY: "ACTIVATE_STAR_ABILITY";
  readonly BLOCK_RESCUE: "BLOCK_RESCUE";
  readonly RESCUE_ATTEMPT: "RESCUE_ATTEMPT";
};
export type ActionType = typeof ActionType[keyof typeof ActionType];
