# ORDIR reference mapping
ORDIR_REFERENCE_ENTRIES = {
    ("'I AM' Has Sent Me", "PoC"): ["Star Card"],
    ("12 Assyrian Siege Army", "FF2"): ["Assyrian"],
    ("12 Assyrian Siege Army", "RR"): ["Assyrian"],
    ("A Royal Priesthood", "PoC"): ["King or Queen of Judah"],
    ("A Wife for Isaac", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Abel", "CW"): ["Cloud Card"],
    ("Abiram, the Stubborn", "IR"): ["Wilderness Character"],
    ("Abraham", "CW"): ["Genesis 12-24 Hero"],
    ("Abraham's Servant to Ur", "LR"): ["Genesis 21-35 Enhancement"],
    ("Abraham's Servant to Ur", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Absalom", "Ki"): ["II Samuel 14-18 Evil Character"],
    ("Adam", "FM"): ["Genesis 1-7 Enhancement"],
    ("Adam, the Exile", "LC"): ["Star Card"],
    ("Adoni-bezek, Thumbless", "II"): ["Canaanite"],
    ("Ahiman, Son of Anak", "FM"): ["Canaanite"],
    ("Ahithophel", "Ki"): ["II Samuel 14-17 Evil Character"],
    ("Alexandrian Ship", "PC"): ["Egyptian"],
    ("Altar of Ahaz", "Pi"): ["Evil Altar"],
    ("Altar of Dagon", "FM"): ["Evil Altar"],
    ("Altar of Dagon", "Pa"): ["Evil Altar"],
    ("Amaziah's Order", "Pi"): ["Prophet"],
    ("Ambushed Moabites", "LC"): ["Fool"],
    ("Amos", "PoC"): ["Major or Minor Prophet"],
    ("Amram & Jochebed", "CW-Alt"): ["Cloud Card"],
    ("Angel at Jerusalem", "Pi"): ["Assyrian"],
    ("Angel from the Sun", "RJ"): ["Martyr"],
    ("Angel in the Path", "RR"): ["Prophet"],
    ("Angel of God", "P"): ["Wilderness Character"],
    ("Anna", "Di"): ["Prophet"],
    ("Answer to Prayer", "FF"): ["Genesis 21-35 Enhancement"],
    ("Answer to Prayer", "LR"): ["Genesis 21-35 Enhancement"],
    ("Antipas", "RJ"): ["Martyr"],
    ("Apphia", "PC"): ["Christ or Jesus in the Title or Scripture Verse"],
    ("Aquila", "EC"): ["Missionary"],
    ("Arba, Greatest Anakim", "II"): ["Canaanite"],
    ("Archippus", "PC"): ["Heretic"],
    ("Arioch", "FF"): ["Prophet"],
    ("Army of Jericho", "CW"): ["Canaanite Site"],
    ("Asaph", "Pi"): ["Involves Music"],
    ("Asaph, the Psalmist", "RR"): ["Involves Music"],
    ("Assyria's Tribute", "FF"): ["Assyrian"],
    ("Assyrian Archer", "FF"): ["Assyrian"],
    ("Assyrian Archer", "LR"): ["Assyrian"],
    ("Assyrian Camp", "LC"): ["Assyrian"],
    ("Assyrian Camp", "Pi"): ["Assyrian"],
    ("Assyrian Officer", "LC"): ["Assyrian"],
    ("Axe", "TP"): ["Babylonian"],
    ("Baal Worship", "FM"): ["Canaanite"],
    ("Balaam's Prophecy", "PoC"): ["Star Card"],
    ("Baptism of Jesus", "Di"): ["Prophet"],
    ("Barabbas", "Pi"): ["Pharisee"],
    ("Barnabas", "EC"): ["Heretic", "Pharisee"],
    ("Bearing Our Sin", "PoC"): ["Prophet"],
    ("Belshazzar's Mother", "PoC"): ["Babylonian", "Prophet"],
    ("Belt of Truth", "Ki"): ["Ephesians 6 Enhancement"],
    ("Belt of Truth", "PC"): ["Ephesians 6 Enhancement"],
    ("Belt of Truth", "Wa"): ["Ephesians 6 Enhancement"],
    ("Bereans", "EC"): ["Missionary"],
    ("Blessings", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Blood of the Lamb", "RJ"): ["Martyr"],
    ("Brass Serpent", "P"): ["Disease"],
    ("Brass Serpent", "PoC"): ["Star Card"],
    ("Breaking Jerusalem's Wall", "RA2"): ["Temple Artifact"],
    ("Breastplate of Righteousness", "A"): ["Ephesians 6 Enhancement"],
    ("Breastplate of Righteousness", "B"): ["Ephesians 6 Enhancement"],
    ("Breastplate of Righteousness", "Ki"): ["Ephesians 6 Enhancement"],
    ("Breastplate of Righteousness", "PC"): ["Ephesians 6 Enhancement"],
    ("Breastplate of Righteousness", "Wa"): ["Ephesians 6 Enhancement"],
    ("Brothers Reunited", "LC"): ["Genesis 21-35 Enhancement"],
    ("Burning of Magic Books", "Ap"): ["Magician"],
    ("Burning of Magic Books", "EC"): ["Magician", "Missionary"],
    ("Burnt Offering", "IR"): ["Offering"],
    ("Burnt Offering", "Pi"): ["Offering"],
    ("Caiaphas the Conspirator", "GC"): ["Pharisee"],
    ("Called to Prophesy", "II"): ["Prophet"],
    ("Canaan", "RA2"): ["Canaanite"],
    ("Canaan, the Cursed", "FM"): ["Canaanite", "Canaanite Site"],
    ("Canaanite Wives", "FM"): ["Canaanite Site"],
    ("Captain Potiphar", "IR"): ["Egyptian"],
    ("Captain of the Chariots", "LC"): ["Syrian"],
    ("Capture and Seize", "PoC"): ["Assyrian"],
    ("Captured by Assyria", "FF"): ["Assyrian"],
    ("Captured by Assyria", "LR"): ["Assyrian"],
    ("Carried into Exile", "Pi"): ["Babylonian"],
    ("Cast into Lion's Den", "PC"): ["Persian"],
    ("Chariot of Fire", "PoC"): ["Prophet"],
    ("Chastisement of the Lord", "PoC"): ["Prophet"],
    ("Cherubim", "FF2"): ["Prophet"],
    ("Cherubim", "LR"): ["Prophet"],
    ("Cherubim", "RR"): ["Prophet"],
    ("Child of Great Wisdom", "Ap"): ["Pharisee"],
    ("Christian Soldier", "PC"): ["Armor of God Enhancement"],
    ("Chronicles of the Kings", "LC"): ["Temple Artifact"],
    ("Citizens of Sychar", "GC"): ["Samaritan"],
    ("Cloud of Witnesses", "CW"): ["Cloud Card"],
    ("Coliseum Lion", "CW"): ["Lion"],
    ("Commitment of Paul", "EC"): ["Paul in the Title"],
    ("Commitment of Paul", "Or"): ["Paul in the Title"],
    ("Concealed Canaanites", "II"): ["Canaanite"],
    ("Conjurers", "PoC"): ["Babylonian", "Magician"],
    ("Conspiring Herodians", "GC"): ["Fool"],
    ("Conspiring Servants", "LC"): ["Fool"],
    ("Continuous Evil", "CW"): ["Genesis 6 Enhancement"],
    ("Corrupt Earth", "FM"): ["Genesis 6 Enhancement"],
    ("Covenant with Philistia", "LC"): ["Genesis 21-35 Enhancement"],
    ("Creeping Deceiver", "Di"): ["Heretic"],
    ("Crooked Ways", "PC"): ["Magician"],
    ("Cupbearer's Complaints", "IR"): ["Egyptian"],
    ("Damascus", "EC"): ["Pharisee", "Syrian"],
    ("Daniel", "CW"): ["Cloud Card"],
    ("David", "RR"): ["Prophet"],
    ("Day of Atonement", "Pi"): ["Offering"],
    ("Death of Firstborn", "PoC"): ["Egyptian"],
    ("Deceit & Vengeance", "FM"): ["Genesis 21-35 Enhancement"],
    ("Deceitful Possessions", "II"): ["Canaanite"],
    ("Delivered", "PoC"): ["Egyptian"],
    ("Desecrate the Temple", "RA"): ["Babylonian"],
    ("Destroying the Temple", "Ki"): ["Babylonian"],
    ("Destruction of Nehushtan", "PoC"): ["Temple Artifact"],
    ("Devouring Lion", "PoC"): ["Star Card"],
    ("Disciples of the Pharisees", "GC"): ["Pharisee"],
    ("Disobedience", "Pa"): ["Genesis 6 Enhancement"],
    ("Distressing People", "LC"): ["Fool", "Star Card"],
    ("Divination", "TP"): ["Magician"],
    ("Doctrine Like Leaven", "RA"): ["Pharisee"],
    ("Doom Speakers", "GC"): ["Pharisee"],
    ("Doomed Canaanites", "PoC"): ["Fool"],
    ("Doomed Conspirators", "PC"): ["Missionary", "Mob"],
    ("Drawn Sword", "FF2"): ["Babylonian"],
    ("Drawn Water", "Wo"): ["Genesis 21-35 Enhancement"],
    ("Dungeon of Malchijah", "RR"): ["Prophet"],
    ("Dutiful Priest", "CW"): ["Offering"],
    ("Egypt", "PoC"): ["Egyptian"],
    ("Egyptian Archer", "Ki"): ["Egyptian"],
    ("Egyptian Army", "PoC"): ["Egyptian"],
    ("Egyptian Horses", "RA"): ["Egyptian"],
    ("Egyptian Treasures", "CW"): ["Egyptian"],
    ("Egyptian Warden", "IR"): ["Egyptian"],
    ("Egyptian Wise Men", "FM"): ["Egyptian"],
    ("Egyptian Wise Men", "Pa"): ["Egyptian"],
    ("Eldad", "IR"): ["Wilderness Character"],
    ("Elijah", "P"): ["Prophet"],
    ("Enoch, the Pure", "LC"): ["Cloud Card"],
    ("Enslaved by Egypt", "H"): ["Egyptian"],
    ("Epaphroditus", "PC"): ["Missionary"],
    ("Epicurean Philosophers", "EC"): ["Scholar or Philosopher in the Title"],
    ("Ethan", "Pi"): ["Involves Music"],
    ("Eyes to See", "PoC"): ["Prophet"],
    ("Ezekiel, the Vindicator", "PoC"): ["Babylonian"],
    ("Face of Death", "Ap"): ["Disease"],
    ("Faith", "PoC"): ["Cloud Card"],
    ("Faith of Abraham", "CW"): ["Cloud Card"],
    ("Faith of Amram & Jochebed", "CW-Alt"): ["Cloud Card"],
    ("Faith of Daniel", "CW"): ["Cloud Card"],
    ("Faith of David", "CW"): ["Cloud Card"],
    ("Faith of Enoch", "CW"): ["Cloud Card"],
    ("Faith of Gideon", "CW"): ["Gideon in the Title"],
    ("Faith of Isaac", "CW"): ["Cloud Card"],
    ("Faith of Jacob", "CW"): ["Cloud Card"],
    ("Faith of Moses' Parents", "CW-Main"): ["Cloud Card"],
    ("Faith of Samuel", "CW"): ["Cloud Card"],
    ("Faith of Sarah", "CW"): ["Cloud Card"],
    ("False Dreams", "PoC"): ["Prophet"],
    ("False Peace", "PoC"): ["Prophet"],
    ("False Prophecy", "PoC"): ["Prophet"],
    ("False Prophesy", "Pr"): ["Prophet"],
    ("Famine in Egypt", "IR"): ["Egyptian"],
    ("Fear has Fallen", "II"): ["Canaanite"],
    ("Fear of Man", "GC"): ["Pharisee"],
    ("Fellowship Offering", "Pi"): ["Offering"],
    ("Filling Zerubbabel's Temple", "FF"): ["Temple Artifact"],
    ("First Fruits", "Pi"): ["Offering"],
    ("Foolish Builder", "GC"): ["Fool"],
    ("Foolish Edomites", "PoC"): ["Fool"],
    ("Forced Labor", "II"): ["Canaanite"],
    ("Foreign Sword", "RA2"): ["Canaanite"],
    ("Foreseen by Samuel", "II"): ["Prophet"],
    ("Forest Fire", "FF2"): ["Babylonian"],
    ("Foretelling Angel", "Pa"): ["Prophet"],
    ("Fortify Site", "RA2"): ["Canaanite", "Canaanite Site"],
    ("Forty Nights", "IR"): ["Wilderness Character"],
    ("Forty Years", "IR"): ["Wilderness Character"],
    ("Fountain of Living Water", "PoC"): ["Star Card"],
    ("Fullness of Time", "PoC"): ["Prophet"],
    ("Gamaliel", "Ap"): ["Pharisee"],
    ("Gates of Jerusalem", "LC"): ["King or Queen of Judah"],
    ("Gates of Jerusalem", "P"): ["King or Queen of Judah"],
    ("Gathered Together", "PoC"): ["Prophet"],
    ("Gathering Soothsayers", "K"): ["Egyptian"],
    ("Gathering the Sanhedrin", "GC"): ["Pharisee"],
    ("Gibeonite Curse", "RA2"): ["Canaanite"],
    ("Gibeonite Trickery", "RA2"): ["Canaanite"],
    ("Gibeonite Trickery", "RR"): ["Canaanite"],
    ("Gideon", "CW"): ["Gideon in the Title"],
    ("Gideon", "J"): ["Gideon in the Title"],
    ("Gideon", "Or"): ["Gideon in the Title"],
    ("Gideon's 300", "P"): ["Gideon in the Title"],
    ("Gideon's Call", "J"): ["Gideon in the Title"],
    ("Gideon's Call", "Pa"): ["Gideon in the Title"],
    ("Gifts and 99 Offerings", "CW"): ["Offering"],
    ("Given Over to Egypt", "RA"): ["Egyptian"],
    ("Given to Egypt", "RR"): ["Egyptian"],
    ("Glad Tidings", "Ap"): ["Disease"],
    ("Glittering Spear", "Ki"): ["Assyrian"],
    ("Glory of the Lord", "P"): ["Temple Artifact"],
    ("Grain Offering", "IR"): ["Offering"],
    ("Grain Offering", "Pi"): ["Offering"],
    ("Greek Philosophers", "Ap"): ["Scholar or Philosopher in the Title"],
    ("Greek Philosophers", "RR"): ["Scholar or Philosopher in the Title"],
    ("Greek Scholars", "Ap"): ["Scholar or Philosopher in the Title"],
    ("Greek Scholars", "RR"): ["Scholar or Philosopher in the Title"],
    ("Grumbling at God", "IR"): ["Wilderness Character"],
    ("Guardian of Your Souls", "RJ"): ["Martyr"],
    ("Guilt Offering", "IR"): ["Offering"],
    ("Guilt Offering", "Pi"): ["Offering"],
    ("Habakkuk", "PoC"): ["Babylonian", "Major or Minor Prophet"],
    ("Habakkuk Stands Watch", "TP"): ["Prophet"],
    ("Hadad, the Exiled", "LC"): ["Egyptian"],
    ("Hagar and Angel at Shur", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Haggai", "PoC"): ["Major or Minor Prophet", "Persian"],
    ("Haman", "P-2019"): ["Persian"],
    ("Haman's Boasting", "PoC"): ["Persian"],
    ("Haman's Gallows", "Di"): ["Persian"],
    ("Hard Bondage", "FM"): ["Egyptian"],
    ("Hard-Hearted Religious Leaders", "Di"): ["Pharisee"],
    ("Head of Gold", "FF"): ["Babylonian"],
    ("Headquarters at Riblah", "Pi"): ["Babylonian"],
    ("Heavenly Temple", "RJ"): ["Martyr"],
    ("Helmet of Salvation", "A"): ["Ephesians 6 Enhancement"],
    ("Helmet of Salvation", "B"): ["Ephesians 6 Enhancement"],
    ("Helmet of Salvation", "Ki"): ["Ephesians 6 Enhancement"],
    ("Helmet of Salvation", "PC"): ["Ephesians 6 Enhancement"],
    ("Helmet of Salvation", "Wa"): ["Ephesians 6 Enhancement"],
    ("Heman", "Pi"): ["Involves Music"],
    ("Herod Agrippa I", "Ap"): ["Herod in the Title"],
    ("Herod Agrippa I", "EC"): ["Herod in the Title"],
    ("Herod Agrippa I", "G"): ["Herod in the Title"],
    ("Herod Agrippa I", "GC"): ["Herod in the Title"],
    ("Herod Agrippa II", "Ap"): ["Herod in the Title"],
    ("Herod Agrippa II", "LR"): ["Herod in the Title"],
    ("Herod Agrippa II", "TP"): ["Herod in the Title"],
    ("Herod Antipas", "Ap"): ["Herod in the Title"],
    ("Herod Antipas", "GC"): ["Herod in the Title"],
    ("Herod Archelaus", "GC"): ["Herod in the Title"],
    ("Herod Philip II", "Ap"): ["Herod in the Title"],
    ("Herod Philip II", "Di"): ["Herod in the Title"],
    ("Herod Philip II", "GC"): ["Herod in the Title"],
    ("Herod the Great", "Ap"): ["Herod in the Title"],
    ("Herod the Great", "Di"): ["Herod in the Title"],
    ("Herod the Great", "GC"): ["Herod in the Title"],
    ("Herod's Executioner", "GC"): ["Herod in the Title"],
    ("Herod's Guard", "GC"): ["Herod in the Title"],
    ("Herod's Sentries", "EC"): ["Herod in the Title"],
    ("Hidden Treasures", "FF"): ["Prophet"],
    ("Hidden Treasures", "RR"): ["Prophet"],
    ("High Places", "LC"): ["Prophet"],
    ("High Priest Annas", "Ap"): ["Pharisee"],
    ("High Priest Annas", "Pi"): ["Pharisee"],
    ("High Priest's Palace", "GC"): ["Pharisee"],
    ("High Priest's Palace", "Pi"): ["Pharisee"],
    ("Hilkiah, the Rebuilder", "RR"): ["Temple Priest"],
    ("His Name is John", "Di"): ["Temple Priest"],
    ("Honor Thy Enemy", "PoC"): ["Persian"],
    ("Hooked and Shackled", "LC"): ["Assyrian", "King or Queen of Judah"],
    ("Hosea", "PoC"): ["Major or Minor Prophet"],
    ("House of Rimmon", "FF"): ["Syrian"],
    ("House of Samuel", "II"): ["Prophet"],
    ("Huldah", "PoC"): ["King or Queen of Judah"],
    ("Hungry Lion", "LC"): ["Lion"],
    ("Idol Worship", "FM"): ["Canaanite"],
    ("Idols of Canaan", "FM"): ["Canaanite"],
    ("Imprisoned Prophet", "FM"): ["Prophet"],
    ("Increasing Numbers", "IR"): ["Wilderness Character"],
    ("Inhabitants Driven Out", "IR"): ["Wilderness Character"],
    ("Inhabiting the Land", "II"): ["Canaanite"],
    ("Inherit Canaan", "II"): ["Canaanite"],
    ("Intervening of Prophecy", "II"): ["Prophet"],
    ("Invoking Terror", "FF2"): ["Magician"],
    ("Invoking Terror", "LR"): ["Magician"],
    ("Iron Chariots", "II"): ["Canaanite"],
    ("Iron Pan", "FF2"): ["Babylonian"],
    ("Irrational Rage", "PoC"): ["Persian"],
    ("Isaiah, Prince of Prophets", "PoC"): ["Star Card"],
    ("Israel's Blessing", "LC"): ["Genesis 21-35 Enhancement"],
    ("Israel's Rebellion", "IR"): ["Wilderness Character"],
    ("Israelites Delivered", "IR"): ["Wilderness Character"],
    ("Jabin, the Assembler", "II"): ["Canaanite"],
    ("Jacob Buries the Foreign gods", "RA"): ["Genesis 21-35 Enhancement"],
    ("Jacob Buries the Idols", "LR"): ["Genesis 21-35 Enhancement"],
    ("Jacob's Dream", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Jacob's New Name", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Jacob's Rods", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Jannes", "FM"): ["Egyptian", "Magician"],
    ("Jared, the Beholder", "LC"): ["Cloud Card"],
    ("Jehoiada the High Priest", "Pi"): ["Temple Artifact"],
    ("Jehu, Message Bringer", "II"): ["Prophet"],
    ("Jericho", "CW"): ["Canaanite", "Cloud Card"],
    ("Jerusalem", "Ap"): ["Pharisee"],
    ("Jochebed", "Wo"): ["Egyptian"],
    ("Joel", "PoC"): ["King or Queen of Judah", "Major or Minor Prophet"],
    ("Joiada, Son of Eliashib", "FF"): ["Offering"],
    ("Jonah", "PoC"): ["Assyrian"],
    ("Journey to Egypt", "Pa"): ["Egyptian"],
    ("Just a Hireling", "GC"): ["Pharisee"],
    ("Just a Hireling", "RA"): ["Pharisee"],
    ("Justin Martyr", "RJ"): ["Martyr"],
    ("Kindness", "Di"): ["Samaritan"],
    ("King Abijam", "RA3"): ["Temple Artifact"],
    ("King Abimelech", "II"): ["Canaanite"],
    ("King Asnappar", "FF"): ["Egyptian", "Syrian"],
    ("King Azariah (Uzziah)", "Ki"): ["II Chronicles 26 Enhancement"],
    ("King Belshazzar", "FF2"): ["Babylonian", "Temple Artifact"],
    ("King Darius, the Mede", "PoC"): ["Persian"],
    ("King Hazael", "LC"): ["Syrian"],
    ("King Hezekiah", "Ki"): ["Assyrian"],
    ("King Hezekiah", "Pi"): ["II Chronicles 29-32 Hero"],
    ("King Jehoash", "RA2"): ["Temple Artifact"],
    ("King Jehoiakin", "Ki"): ["Babylonian"],
    ("King Jehoshaphat", "Pi"): ["II Chronicles 17-20 Hero"],
    ("King Manasseh", "Di"): ["Magician"],
    ("King Rezin", "PoC"): ["Syrian"],
    ("King Sennacherib", "LC"): ["Assyrian"],
    ("King Shalmaneser III", "PoC"): ["Assyrian"],
    ("King So", "Ki"): ["Egyptian"],
    ("King Tiglath-Pileser III", "PoC"): ["Assyrian"],
    ("King Xerxes", "PoC"): ["Persian"],
    ("King Zedekiah", "Ki"): ["Babylonian"],
    ("King of Tyrus", "P"): ["Canaanite"],
    ("King of Tyrus", "PoC"): ["Canaanite"],
    ("King's Signet Ring", "LC"): ["King or Queen of Judah"],
    ("Kings of the Earth", "RJ"): ["Nationality"],
    ("Korah, the Rebellious", "IR"): ["Wilderness Character"],
    ("Lacking Prophecy", "PoC"): ["Prophet"],
    ("Lamech, Rest Seeker", "LC"): ["Star Card"],
    ("Lamenting", "Pa"): ["Involves Music"],
    ("Land Dispute", "LC"): ["Genesis 21-35 Enhancement"],
    ("Laughter", "Wo"): ["Genesis 21-35 Enhancement"],
    ("Letter to the Hebrews", "CW"): ["Cloud Card"],
    ("Letter to the Philippians", "PC"): ["Missionary"],
    ("Letters to the Thessalonians", "EC"): ["Heretic"],
    ("Lions' Den", "PoC"): ["Lion", "Persian"],
    ("Lost Soul", "II"): ["Canaanite"],
    ("Lost Soul", "IR"): ["Wilderness Character"],
    ("Lost Soul", "K"): ["Egyptian"],
    ("Lost Soul", "LC"): ["Star Card"],
    ("Lost Soul", "PoC"): ["Star Card"],
    ("Love at First Sight", "LC"): ["Genesis 21-35 Enhancement"],
    ("Love at First Sight", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Love for Rachel", "Wo"): ["Genesis 21-35 Enhancement"],
    ("Magic Charms", "P"): ["Magician"],
    ("Magic Charms", "TP"): ["Magician"],
    ("Magicians' Snakes", "Di"): ["Egyptian", "Magician"],
    ("Magicians' Snakes", "FM"): ["Egyptian", "Magician"],
    ("Magicians' Staves", "FM"): ["Egyptian", "Magician"],
    ("Malachi", "PoC"): ["Major or Minor Prophet", "Persian", "Star Card"],
    ("Manasseh's Altar", "FM"): ["Evil Altar"],
    ("Mary, Holy Virgin", "GC"): ["Star Card"],
    ("Medad", "IR"): ["Wilderness Character"],
    ("Meekness of Isaac", "Or"): ["Genesis 21-35 Enhancement"],
    ("Meeting the Messiah", "GC"): ["Samaritan"],
    ("Melchizedek", "CW"): ["Cloud Card"],
    ("Melchizedek", "PoC"): ["Star Card"],
    ("Mene, Mene, Tekel, Upharsin", "PoC"): ["Babylonian"],
    ("Merodach Worship", "Pi"): ["Babylonian"],
    ("Messenger Angel", "Pa"): ["Prophet"],
    ("Micah", "PoC"): ["King or Queen of Judah", "Major or Minor Prophet"],
    ("Mighty Men", "PoC"): ["Prophet"],
    ("Mimicking Miracles", "CW"): ["Magician"],
    ("Miracle of Healing", "Ap"): ["Disease"],
    ("Miraculous Handkerchiefs", "Ap"): ["Disease"],
    ("Miriam", "PoC"): ["Involves Music"],
    ("Missionary Ship", "EC"): ["Missionary"],
    ("Moses", "CW"): ["Cloud Card"],
    ("Moses", "P"): ["Cloud Card"],
    ("Moses' Parents", "CW-Main"): ["Cloud Card"],
    ("Moses' Rod", "G"): ["Plague"],
    ("Moses' Staff", "PoC"): ["Plague"],
    ("Moses, the Servant", "IR"): ["Wilderness Character"],
    ("Mounted Forces", "PoC"): ["Assyrian", "Babylonian"],
    ("Murderous Command", "K"): ["Egyptian"],
    ("Music Leader", "P"): ["Involves Music"],
    ("Music Leader", "PC"): ["Involves Music"],
    ("Musicians' Chambers", "RA"): ["Involves Music"],
    ("Naaman's Horses", "RR"): ["Prophet", "Syrian"],
    ("Nahshon, the Blacksmith", "LC"): ["Star Card"],
    ("Nahum", "PoC"): ["Assyrian", "Major or Minor Prophet"],
    ("Nebuchadnezzar", "PoC"): ["Babylonian"],
    ("Nebuchadnezzar's Dream", "FF"): ["Babylonian"],
    ("Negev Lions", "PoC"): ["Lion"],
    ("Nergalsharezer", "FF"): ["Babylonian"],
    ("Nicanor", "EC"): ["Deacon"],
    ("Nicodemus", "Ap"): ["Pharisee"],
    ("Nicodemus", "Di"): ["Pharisee"],
    ("Night Raid", "RR"): ["Syrian"],
    ("Nimrod, the Mighty", "CW"): ["Assyrian"],
    ("Nimrod, the Mighty 13", "CW"): ["Babylonian"],
    ("Nineveh", "PoC"): ["Assyrian"],
    ("Ninevites", "PoC"): ["Prophet"],
    ("Ninevites Repent", "PoC"): ["Assyrian"],
    ("Not Among You", "II"): ["Canaanite"],
    ("Number of the Beast", "Wa"): ["Prophet"],
    ("Numerous as the Stars", "PoC"): ["Star Card"],
    ("Nunc Dimittis", "Di"): ["Prophet"],
    ("Obadiah", "PoC"): ["Major or Minor Prophet"],
    ("Obadiah's Caves", "RA"): ["Prophet"],
    ("Obadiah's Hidden 100", "II"): ["Prophet"],
    ("Offering Your Son", "PoC"): ["Genesis 21-35 Enhancement"],
    ("Offering of Wrongdoing", "IR"): ["Wilderness Character"],
    ("Og, King of Bashan", "FM"): ["Canaanite"],
    ("Omen Interpreter", "IR"): ["Magician"],
    ("Onesiphorus", "PC"): ["Missionary"],
    ("Paladin", "PC"): ["Armor of God Enhancement"],
    ("Paul", "Ap"): ["Paul in the Title"],
    ("Paul", "P"): ["Paul in the Title"],
    ("Paul's Books and Parchment", "PC"): ["Paul in the Title"],
    ("Paul's Books and Parchments", "Ap"): ["Paul in the Title"],
    ("Paul's Disciples", "EC"): ["Paul in the Title"],
    ("Paul's Girdle", "Pr"): ["Paul in the Title"],
    ("Paul's Nephew", "PC"): ["Paul in the Title"],
    ("Peace Offering", "IR"): ["Offering"],
    ("Peleg, the Divider", "LC"): ["Star Card"],
    ("Persian Archers", "PoC"): ["Persian"],
    ("Persian Conquerors", "PoC"): ["Persian"],
    ("Persian Horsemen", "PoC"): ["Persian"],
    ("Persian Horses", "PoC"): ["Persian"],
    ("Peter's Mother-In-Law", "Ap"): ["Disease"],
    ("Peter's Shadow", "Ap"): ["Disease"],
    ("Pharaoh Hophra", "Pi"): ["Babylonian"],
    ("Pharaoh Shishak", "RR"): ["Egyptian"],
    ("Pharaoh's Army", "K"): ["Egyptian"],
    ("Pharaoh's Baker", "IR"): ["Egyptian"],
    ("Pharaoh's Cupbearer", "IR"): ["Egyptian"],
    ("Pharaoh's Dream", "IR"): ["Egyptian"],
    ("Pharaoh's Officials", "K"): ["Egyptian"],
    ("Pharaoh's Servants", "PoC"): ["Egyptian"],
    ("Pharaoh's Throne Room", "IR"): ["Egyptian"],
    ("Pharaoh's Throne Room", "Pi"): ["Egyptian"],
    ("Pharisees", "Ap"): ["Pharisee"],
    ("Pharisees", "LR"): ["Pharisee"],
    ("Philemon", "PC"): ["Heretic"],
    ("Philip of Bethsaida", "GC"): ["Martyr"],
    ("Philip the Evangelist", "Ap"): ["Deacon"],
    ("Philip the Evangelist", "EC"): ["Deacon", "Magician"],
    ("Phygellus", "PC"): ["Heretic"],
    ("Pillar of Salt", "FM"): ["Canaanite Site"],
    ("Pithom", "P"): ["Egyptian"],
    ("Plague of Boils", "LC"): ["Plague"],
    ("Plague of Lice", "LC"): ["Plague"],
    ("Plot to Kill", "RJ"): ["Pharisee"],
    ("Potential in the Land", "IR"): ["Wilderness Character"],
    ("Potiphera, Priest of On", "IR"): ["Egyptian"],
    ("Potiphera, Priest of On", "Pi"): ["Egyptian"],
    ("Prayer and Fasting", "EC"): ["Missionary"],
    ("Pretension", "GC"): ["Pharisee"],
    ("Pretension", "TP"): ["Pharisee"],
    ("Pride of Lions", "P"): ["Lion"],
    ("Pride of Simon", "EC"): ["Magician"],
    ("Prince of Persia", "Di"): ["Persian"],
    ("Prince of Tyrus", "P"): ["Canaanite"],
    ("Priscilla", "EC"): ["Missionary"],
    ("Prochorus", "EC"): ["Deacon"],
    ("Prophets of Gibeath", "P"): ["Involves Music", "Prophet"],
    ("Prophets of Samaria", "PoC"): ["Prophet"],
    ("Protection of Jerusalem", "FF2"): ["Assyrian"],
    ("Proud Pharisee", "TP"): ["Pharisee"],
    ("Quail from Above", "IR"): ["Wilderness Character"],
    ("Raamses", "FM"): ["Egyptian"],
    ("Razor", "FF2"): ["Assyrian"],
    ("Rebekah meets Isaac", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Rebellious Israelites", "IR"): ["Wilderness Character"],
    ("Reclaimed by Egypt", "PoC"): ["Egyptian"],
    ("Redeeming Branch", "PoC"): ["Star Card"],
    ("Resurrection of Martyrs", "RJ"): ["Martyr"],
    ("Retribution for Sin", "II"): ["Prophet"],
    ("Rezon, Son of Eliada", "LC"): ["Syrian"],
    ("Ruthless", "FF"): ["Egyptian"],
    ("Sabbath Breaker", "IR"): ["Wilderness Character"],
    ("Saint of Virtue", "PC"): ["Armor of God Enhancement"],
    ("Samaritan Water Jar", "GC"): ["Samaritan"],
    ("Samaritan Water Jar", "TP"): ["Samaritan"],
    ("Samuel", "CW"): ["Cloud Card"],
    ("Samuel, Born of Prayer", "II"): ["Prophet"],
    ("Sanhedrin", "Ap"): ["Pharisee"],
    ("Sanhedrin", "EC"): ["Pharisee"],
    ("Scapegoat", "Pi"): ["Offering"],
    ("Scapegoat", "PoC"): ["Offering"],
    ("Scraps Under the Table", "II"): ["Canaanite"],
    ("Scribe", "Di"): ["Pharisee"],
    ("Search", "FF"): ["Prophet"],
    ("Search", "LR"): ["Prophet"],
    ("Secundus", "EC"): ["Missionary"],
    ("Seize Him!", "RJ"): ["Pharisee"],
    ("Seized by Babylon", "PoC"): ["Babylonian"],
    ("Self-Righteous Prayer", "Di"): ["Pharisee"],
    ("Self-Righteous Prayer", "GC"): ["Pharisee"],
    ("Send for Egyptians", "IR"): ["Egyptian"],
    ("Sennacherib Blasphemes", "LC"): ["Assyrian"],
    ("Seraiah the High Priest", "Pi"): ["Babylonian"],
    ("Seraph", "LR"): ["Prophet"],
    ("Seraph", "RA"): ["Prophet"],
    ("Seraph with a Live Coal", "FF2"): ["Isaiah 6 Enhancement"],
    ("Sheshai, Son of Anak", "FM"): ["Canaanite"],
    ("Shield of Faith", "A"): ["Ephesians 6 Enhancement"],
    ("Shield of Faith", "B"): ["Ephesians 6 Enhancement"],
    ("Shield of Faith", "Ki"): ["Ephesians 6 Enhancement"],
    ("Shield of Faith", "PC"): ["Ephesians 6 Enhancement"],
    ("Shield of Faith", "Wa"): ["Bows, Arrows, Spears, Javelins and Darts", "Ephesians 6 Enhancement"],
    ("Shobach", "P"): ["Syrian"],
    ("Shobach, the Commander", "RR"): ["Syrian"],
    ("Shoes of Peace", "A-Ul"): ["Ephesians 6 Enhancement"],
    ("Shoes of Peace", "C"): ["Ephesians 6 Enhancement"],
    ("Shoes of Peace", "D"): ["Ephesians 6 Enhancement"],
    ("Shoes of Peace", "F"): ["Ephesians 6 Enhancement"],
    ("Shoes of Peace", "P"): ["Ephesians 6 Enhancement"],
    ("Shoes of Peace", "PC"): ["Ephesians 6 Enhancement"],
    ("Siegeworks", "FF2"): ["Assyrian"],
    ("Simeon", "Di"): ["Prophet"],
    ("Simeon", "Wa"): ["Prophet"],
    ("Simeon, the Devout", "GC"): ["Prophet"],
    ("Simon the Host", "GC"): ["Pharisee"],
    ("Sin Offering", "IR"): ["Offering"],
    ("Sin Offering", "Pi"): ["Offering"],
    ("Sisera's Army", "CW"): ["Canaanite"],
    ("Slayer's Glee", "RJ"): ["Canaanite", "Egyptian"],
    ("Soldiers of Zobah", "CW"): ["Syrian"],
    ("Solomon's Oppression", "LC"): ["King or Queen of Judah"],
    ("Solomon's Temple", "P"): ["Temple Artifact"],
    ("Solomon's Temple", "Pa"): ["Temple Artifact"],
    ("Solomon's Temple", "RA3"): ["King or Queen of Judah", "Temple Artifact"],
    ("Soothsayers of Babylon", "PoC"): ["Magician"],
    ("Spirit of Elijah", "PoC"): ["Prophet"],
    ("Spiritual Protection", "Pa"): ["Armor of God Enhancement"],
    ("Spiritual Warfare", "AW"): ["Ephesians 6 Enhancement"],
    ("Stand Firm", "EC"): ["Heretic"],
    ("Star 119 of Bethlehem", "GC"): ["Star Card"],
    ("Star 119 of Bethlehem", "P"): ["Star Card"],
    ("Steadfastness of Peter", "C"): ["Disease"],
    ("Stoic Philosophers", "EC"): ["Scholar or Philosopher in the Title"],
    ("Stolen Blessing", "LC"): ["Genesis 21-35 Enhancement"],
    ("Stoning of Stephen", "EC"): ["Pharisee"],
    ("Stormy Seas", "PC"): ["Egyptian"],
    ("Strict Sabbath", "GC"): ["Pharisee"],
    ("Struck & Scattered", "II"): ["Canaanite"],
    ("Summoned to Interpret", "PoC"): ["Magician"],
    ("Sun Worship", "FM"): ["Egyptian"],
    ("Supercilious Scribes", "GC"): ["Pharisee"],
    ("Swift Horses", "FF"): ["Babylonian"],
    ("Swift Horses", "RR"): ["Babylonian"],
    ("Sword of the Spirit", "Ki"): ["Ephesians 6 Enhancement"],
    ("Sword of the Spirit", "PC"): ["Ephesians 6 Enhancement"],
    ("Sychar", "GC"): ["Samaritan"],
    ("Syrian Archer", "Ki"): ["Syrian"],
    ("Syrian Archer", "LR"): ["Syrian"],
    ("Syrian Mercenaries", "CW"): ["Syrian"],
    ("Syrian Reinforcements", "CW"): ["Syrian"],
    ("Syrian Victory", "Ki"): ["Syrian"],
    ("Talmai, Son of Anak", "FM"): ["Canaanite"],
    ("Temple Dedication", "RA3"): ["Temple Artifact"],
    ("Temple Priests", "RA3"): ["Temple Artifact"],
    ("Temple Priests", "RR"): ["Temple Artifact"],
    ("Temple of Nisroch", "Ki"): ["Assyrian"],
    ("Tenants Kill the Son", "Di"): ["Pharisee"],
    ("Tested by Fire", "PoC"): ["Magician", "Prophet"],
    ("The Angel of His Presence", "PoC"): ["Major or Minor Prophet"],
    ("The Angel of the Winds", "CW"): ["Cloud Card"],
    ("The Angel of the Winds", "P"): ["Cloud Card"],
    ("The Assyrian Spoilers", "RA"): ["Assyrian"],
    ("The Babylonian Merchants", "PoC"): ["Babylonian"],
    ("The Bear", "PoC"): ["Babylonian", "Egyptian", "Persian"],
    ("The Bear", "RA"): ["Babylonian", "Persian"],
    ("The Brood of Vipers", "GC"): ["Pharisee"],
    ("The Chief Priests", "RJ"): ["Pharisee"],
    ("The Child is Born", "GC"): ["Star Card"],
    ("The Chosen Warriors", "IR"): ["Wilderness Character"],
    ("The Clashing King", "II"): ["Canaanite"],
    ("The Coming Prince", "PoC"): ["Star Card"],
    ("The Coming Prophet", "PoC"): ["Prophet", "Star Card"],
    ("The Courtyard", "IR"): ["Wilderness Character"],
    ("The Crafty Gibeonites", "II"): ["Canaanite"],
    ("The Destroyer", "PoC"): ["Plague"],
    ("The Emmaus Road", "PoC"): ["Star Card"],
    ("The Ends of the Earth", "RJ"): ["Missionary"],
    ("The Ephesian Elders", "PC"): ["Heretic", "Magician"],
    ("The Ethiopian Treasurer", "EC"): ["Deacon"],
    ("The Five Kings", "II"): ["Canaanite"],
    ("The Frog Demons", "RJ"): ["Revelation 12-19 Evil Character"],
    ("The Generous Givers", "PC"): ["Missionary"],
    ("The Goat with Horn", "Di"): ["Persian"],
    ("The Golden Altar", "RJ"): ["Martyr"],
    ("The Hard-Hearted Pharaoh", "CW"): ["Egyptian"],
    ("The Imperial Guard", "RA"): ["Babylonian"],
    ("The Judean Mediums", "P"): ["Magician"],
    ("The Judean Mediums", "PC"): ["Magician"],
    ("The Lord Provides", "LC"): ["Genesis 21-35 Enhancement"],
    ("The Lying Prophet", "PoC"): ["Prophet"],
    ("The Lying Spirit", "FM"): ["Prophet"],
    ("The Magi", "GC"): ["Star Card"],
    ("The Plotting Pharisees", "RJ"): ["Pharisee"],
    ("The Prophet of God", "K"): ["Prophet"],
    ("The Prophetess", "PoC"): ["Prophet"],
    ("The Proselytizers", "GC"): ["Pharisee"],
    ("The Rab-saris", "LC"): ["Assyrian"],
    ("The Rabsaris", "RA"): ["Assyrian"],
    ("The Rabshakeh Attacks", "Ki"): ["Assyrian"],
    ("The Rabshakeh's Threats", "LC"): ["Assyrian"],
    ("The Ram with Two Horns", "Di"): ["Babylonian", "Persian"],
    ("The Seventy Elders", "IR"): ["Wilderness Character"],
    ("The Shunammite Woman", "PoC"): ["Prophet"],
    ("The Strong Force", "RA"): ["Syrian"],
    ("The Strong Force", "RR"): ["Syrian"],
    ("The Sword of Gideon", "J"): ["Gideon in the Title"],
    ("The Tartan", "LC"): ["Assyrian"],
    ("The Victorious Being", "II"): ["Prophet"],
    ("The Watchman", "P"): ["Major or Minor Prophet"],
    ("The Watchman", "RR"): ["Prophet"],
    ("The Winged Leopard", "PoC"): ["Persian"],
    ("The Winged Leopard", "RA"): ["Persian"],
    ("The Winged Lion", "PoC"): ["Assyrian", "Babylonian"],
    ("The Winged Lion", "RA"): ["Assyrian", "Babylonian"],
    ("The Woman at the Well", "GC"): ["Samaritan"],
    ("The Woman of Thebez", "II"): ["Canaanite"],
    ("The Word Spreads", "H"): ["Deacon"],
    ("The gods of Egypt", "IR"): ["Egyptian"],
    ("The gods of Egypt", "Pa"): ["Egyptian"],
    ("Third Bowl of Wrath", "RJ"): ["Martyr"],
    ("Timon", "EC"): ["Deacon"],
    ("Timothy", "EC"): ["Missionary"],
    ("Titus Justus", "EC"): ["Missionary"],
    ("Told Before Truth", "II"): ["Prophet"],
    ("Tower of Thebez", "II"): ["Canaanite"],
    ("Tower of Thebez", "RA2"): ["Canaanite"],
    ("Trust", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Two Bears", "LR"): ["Prophet"],
    ("Two Bears", "P"): ["Prophet"],
    ("Two Bears", "RA"): ["Prophet"],
    ("Two Thousand Horses", "RR"): ["Assyrian"],
    ("Untouchable", "GC"): ["Pharisee"],
    ("Vain Vision", "PoC"): ["Prophet"],
    ("Vain Vision", "Pr"): ["Prophet"],
    ("Vine-Grower's Rebellion", "GC"): ["Pharisee", "Prophet"],
    ("Violent Tendencies", "FM"): ["Genesis 6 Enhancement"],
    ("Vow for Samuel", "II"): ["Prophet"],
    ("Wandering Israelites", "IR"): ["Wilderness Character"],
    ("Well Reopened", "F"): ["Genesis 21-35 Enhancement"],
    ("Well Reopened", "TP"): ["Genesis 21-35 Enhancement"],
    ("What Will You Do?", "II"): ["Canaanite"],
    ("Who is Without Sin?", "GC"): ["Pharisee"],
    ("Wickedness Abounds", "CW"): ["Genesis 6 Enhancement"],
    ("Wickedness Abounds", "Pi"): ["Genesis 6 Enhancement"],
    ("Widows' Tables", "EC"): ["Deacon"],
    ("Wings", "AW"): ["Disease"],
    ("Wisdom", "PC"): ["Heretic"],
    ("Withered Plant", "PoC"): ["Prophet"],
    ("Wolves in Sheep's Clothing", "Di"): ["Heretic"],
    ("Word of Their Testimony", "CW"): ["Prophet"],
    ("Worship of Nisroch", "LC"): ["Assyrian"],
    ("Wrestling with God", "Pa"): ["Genesis 21-35 Enhancement"],
    ("Yoke of Iron", "RR"): ["Babylonian"],
    ("Zadok", "PoC"): ["Prophet"],
    ("Zebul, the Fraud", "II"): ["Canaanite"],
    ("Zechariah, the Renewer", "PoC"): ["Major or Minor Prophet", "Star Card", "Temple Priest"],
    ("Zephaniah", "PoC"): ["King or Queen of Judah", "Major or Minor Prophet"],
    ("Zeresh Advises Haman", "RA"): ["Persian"],
    ("Zerubbabel's Temple", "FF"): ["Temple Artifact", "Zechariah Card"],
    ("Zerubbabel's Temple", "LC"): ["Offering", "Zechariah Card"],
}
