ORDIR_MAP = {
    "Aaron, Peacemaker": ["Duplicate Card"],
    "Abiathar": ["Duplicate Card"],
    "Abiathar, the Survivor": ["Duplicate Card"],
    "Abiezer, the Anathothite": ["Duplicate Card"],
    "Abihu, the Disobedient": ["Duplicate Card"],
    "Abiram": ["Duplicate Card"],
    "Abiram, the Stubborn": ["Duplicate Card"],
    "Abishai, Chief of Thirty": ["Duplicate Card"],
    "Adino, the Eznite": ["Duplicate Card"],
    "Admiral": ["Demon"],
    "Adoni-bezek, Thumbless": ["Canaanite"],
    "Adonijah": ["Duplicate Card"],
    "Ahaziah": ["Depicting an Idol"],
    "Ahimaaz, the Swift": ["Duplicate Card"],
    "Ahimelech, Chief Priest": ["Duplicate Card"],
    "Ahimelech, Priest at Nob": ["Duplicate Card"],
    "Ahimelek the Hittite": ["Canaanite"],
    "Amariah the High Priest": ["Duplicate Card"],
    "Amorite Invasion": ["Fought in an Earthly Battle"],
    "Angel at Bethesda": ["Angel"],
    "Angel at the Tomb (Wa)": ["Angel"],
    "Angel of God": ["Angel"],
    "Angel of His Presence": ["Angel"],
    "Angel of Might": ["Angel"],
    "Angel of Revelation": ["Generic Character"],
    "Angel of the Harvest": ["Angel"],
    "Angel of the Waters": ["Angel"],
    "Arba, Greatest Anakim": ["Canaanite"],
    "Archelaus (Di)": ["Duplicate Card"],
    "Archers of Kedar": ["Generic Character"],
    "Arianna": ["Angel"],
    "Armorbearer": ["Fought in an Earthly Battle"],
    "Army of Simeonites": ["Generic Character"],
    "Asahel, Swift-Footed": ["Duplicate Card"],
    "Asaph": ["Duplicate Card"],
    "Asher": ["Duplicate Card"],
    "Asher, the Rich": ["Duplicate Card"],
    "Assyria": ["Assyrian"],
    "Athaliah": ["Duplicate Card"],
    "Baal Worship": ["Canaanite"],
    "Babylon": ["Babylonian"],
    "Bathsheba": ["Duplicate Card"],
    "Bear": ["Animal"],
    "Benaiah, Lion Slayer": ["Duplicate Card"],
    "Benjamin": ["Duplicate Card"],
    "Benjamin, the Young": ["Duplicate Card"],
    "Bera, King of Sodom": ["Canaanite"],
    "Bezaleel": ["Duplicate Card"],
    "Bezalel, the Builder": ["Duplicate Card"],
    "Blinding Demon": ["Demon"],
    "Blood Avenger": ["Generic Character"],
    "Book of Nathan": ["Based on Prophecy"],
    "Book of the Wars": ["Depicting a Weapon"],
    "Buckler (Wa)": ["Fought in an Earthly Battle"],
    "Burning Incense": ["Nativity Card"],
    "Caleb, the Rewarded": ["Duplicate Card"],
    "Canaan": ["Canaanite"],
    "Canaan, the Cursed": ["Canaanite"],
    "Captain Potiphar": ["Duplicate Card"],
    "Captive Priest": ["Generic Character"],
    "Captive Princes": ["Generic Character"],
    "Chenaniah": ["Duplicate Card"],
    "Children": ["Generic Character"],
    "Claudia": ["Duplicate Card"],
    "Cloud of Witnesses": ["Cloud Card"],
    "Coliseum": ["Animal"],
    "Coliseum Lion": ["Animal"],
    "Complainers": ["Gender"],
    "Concealed Canaanites": ["Canaanite"],
    "Covenant Keepers": ["Generic Character"],
    "Creeping Deceiver": ["Generic Character"],
    "Crippling Demon": ["Demon"],
    "Cubus": ["Demon"],
    "Damascus (EC)": ["Pharisee"],
    "Dan, Justice of Peace": ["Duplicate Card"],
    "Dathan": ["Duplicate Card"],
    "Dathan, the Follower": ["Duplicate Card"],
    "Deafening Spirit": ["Demon"],
    "Death & Hades": ["Duplicate Card"],
    "Deborah": ["Duplicate Card"],
    "Deborah, the Victorious": ["Duplicate Card"],
    "Deceitful Possessions": ["Canaanite"],
    "Deceiving Spirit": ["Demon"],
    "Defrauders": ["Generic Character"],
    "Deluders": ["Generic Character"],
    "Demon behind the Idol": ["Demon"],
    "Demon in Armor": ["Demon"],
    "Destroying Angel": ["Angel"],
    "Devouring Lion": ["Animal"],
    "Disbelieving Sadducees": ["Generic Character"],
    "Doctrine Like Leaven": ["Pharisee"],
    "Doeg, the Slaughterer": ["Duplicate Card"],
    "Doomed Canaanites": ["Canaanite"],
    "Doubt": ["Demon"],
    "Dreamers": ["Generic Character"],
    "Dutiful Priest": ["Generic Character"],
    "Eldad": ["Based on Prophecy"],
    "Eleazar, son of Aaron": ["House of Eleazar"],
    "Eleazar, the Ahohite": ["Duplicate Card"],
    "Eli": ["Angel"],
    "Elisabeth": ["Duplicate Card"],
    "Enemies to the East": ["Generic Character"],
    "Esau": ["Duplicate Card"],
    "Esau, the Hunter": ["Duplicate Card"],
    "Esther, the Courageous (PoC)": ["Duplicate Card"],
    "Evil Sacrifices": ["Depicting an Idol"],
    "Ezra": ["Duplicate Card"],
    "Faith of David": ["Giant"],
    "False Leaders (PoC)": ["Generic Character"],
    "False Teacher": ["Generic Character"],
    "Fear has Fallen": ["Canaanite"],
    "Fiery Serpents": ["Animal"],
    "Fire Foxes": ["Animal"],
    "Foolish Shepherd": ["Generic Character"],
    "Forced Labor": ["Canaanite"],
    "Foreign Spearman": ["Generic Character"],
    "Foreign Sword": ["Canaanite"],
    "Foreign Wives": ["Canaanite"],
    "Foretelling Angel": ["Angel"],
    "Formal Training": ["Nativity Card"],
    "Gathering Angel": ["Angel"],
    "Gibeonite Curse": ["Canaanite"],
    "Gibeonite Delegates": ["Canaanite"],
    "Good Samaritan": ["Duplicate Card"],
    "Greek Scholars": ["Generic Character"],
    "Guiding Angel": ["Angel"],
    "Hamor": ["Canaanite"],
    "Harbingers": ["Angel"],
    "Hard-Hearted Religious Leaders (Di)": ["Pharisee"],
    "Helez, the Paltite": ["Duplicate Card"],
    "High Priest's Maid": ["Duplicate Card"],
    "Hilkiah the High Priest": ["Duplicate Card"],
    "Hophni, son of Eli": ["Duplicate Card"],
    "Hophni, the Profane": ["Duplicate Card"],
    "Hosts of Heaven": ["Angel"],
    "Humble Seeker": ["Generic Character"],
    "Idol Worship": ["Canaanite"],
    "Idols of Canaan": ["Canaanite"],
    "Impostors": ["Gender"],
    "Imprisoned": ["Generic Character"],
    "Inhabiting the Land": ["Canaanite"],
    "Inherit Canaan": ["Canaanite"],
    "Injuring Demon": ["Demon"],
    "Ira, the Tekoite": ["Duplicate Card"],
    "Iron Chariots": ["Canaanite"],
    "Ishmaiah the Gibeonite": ["Canaanite"],
    "Israelite Archer": ["Generic Character"],
    "Ithamar, son of Aaron": ["House of Ithamar"],
    "Jabin, the Assembler": ["Canaanite"],
    "Jackals": ["Animal"],
    "Jael": ["Duplicate Card"],
    "James (half-brother of Jesus": ["Duplicate Card"],
    "James Son of Zebedee (Ap)": ["Duplicate Card"],
    "James, Leader in Jerusalem": ["Duplicate Card"],
    "Jehoiada the High Priest": ["Duplicate Card"],
    "Jericho": ["Canaanite"],
    "Joab, the General": ["Duplicate Card"],
    "Job": ["Duplicate Card"],
    "Joseph of Arimathea": ["Duplicate Card"],
    "Joseph the Carpenter": ["Duplicate Card"],
    "Joseph, the Blessed": ["Duplicate Card"],
    "Joshua the High Priest": ["Duplicate Card"],
    "Joshua, Son of Nun": ["Duplicate Card"],
    "Joshua, the Commander": ["Duplicate Card"],
    "Judah": ["Duplicate Card"],
    "Judaizers": ["Generic Character"],
    "Jude": ["Generic Character"],
    "Justice Bringer": ["Angel"],
    "Kidron Valley": ["Depicting an Idol"],
    "King Abijah": ["Duplicate Card"],
    "King Abijam": ["Duplicate Card"],
    "King Abimelech": ["Canaanite"],
    "King Ahab": ["Duplicate Card"],
    "King Ahaziah": ["Depicting an Idol", "Duplicate Card"],
    "King Ahaziah (PC)": ["Depicting an Idol"],
    "King Amon (Di)": ["Depicting an Idol"],
    "King Azariah (Uzziah)": ["Duplicate Card"],
    "King Hiram": ["Canaanite"],
    "King Jehoiakim": ["Duplicate Card"],
    "King Jehoram": ["Duplicate Card"],
    "King Josiah": ["Duplicate Card"],
    "King Jotham": ["Duplicate Card"],
    "King Manasseh": ["Duplicate Card"],
    "King Shishak": ["Duplicate Card"],
    "King So": ["Duplicate Card"],
    "King of Tyrus": ["Canaanite"],
    "Kinsman Redeemer": ["Generic Character"],
    "Kira": ["Angel"],
    "Korah": ["Duplicate Card"],
    "Korah, the Rebellious": ["Duplicate Card"],
    "Legion of Angels": ["Angel"],
    "Levi": ["Animal"],
    "Levi, the Fierce": ["Duplicate Card"],
    "Leviathan": ["Animal"],
    "Lions": ["Animal"],
    "Lot": ["Canaanite"],
    "Lying Spirit": ["Demon"],
    "Manasseh": ["Duplicate Card"],
    "Mary Magdalene (Wo)": ["Connected with Demons"],
    "Mary of Bethany": ["Duplicate Card"],
    "Mary the Mother of James": ["Duplicate Card"],
    "Medad": ["Based on Prophecy"],
    "Media": ["Duplicate Card"],
    "Medium in Endor": ["Generic Character"],
    "Men of Judah": ["Generic Character"],
    "Men of Moab": ["Generic Character"],
    "Mentor": ["Duplicate Card"],
    "Messenger Angel": ["Angel"],
    "Messenger of Satan": ["Demon"],
    "Michael, Chief Prince": ["Angel"],
    "Michal": ["Connected with David"],
    "Moabite Army": ["Generic Character"],
    "Moabite Marauders": ["Generic Character"],
    "Mocking Soldiers (J)": ["Generic Character"],
    "Morg": ["Demon"],
    "Morgan": ["Demon"],
    "Moses, the Servant": ["Duplicate Card"],
    "Moths": ["Animal"],
    "Multitude": ["Angel"],
    "Naaman": ["Duplicate Card"],
    "Nadab": ["Duplicate Card"],
    "Nadab, the Wicked": ["Duplicate Card"],
    "Naharai": ["Duplicate Card"],
    "Naharai, the Beerothite": ["Duplicate Card"],
    "Nathan": ["Based on Prophecy"],
    "Necromancer": ["Generic Character"],
    "Negev Lions": ["Animal"],
    "Nehemiah": ["Nehemiah Card"],
    "Not Among You": ["Canaanite"],
    "Obsidian Minion": ["Demon"],
    "Og, King of Bashan": ["Canaanite"],
    "Oholiab": ["Duplicate Card"],
    "Oholiab, the Engraver": ["Duplicate Card"],
    "Oppressive Women": ["Generic Character"],
    "Othniel, Son of Kenaz": ["Duplicate Card"],
    "Pagan Priest": ["Depicting an Evil Altar"],
    "Paladin": ["Angel"],
    "Paladin, the Fighter": ["Angel"],
    "Persian Archers": ["Generic Character"],
    "Philistine Diviners": ["Generic Character"],
    "Philistine Garrison": ["Generic Character"],
    "Philistine Priests": ["Generic Character"],
    "Philistine Soothsayers": ["Generic Character"],
    "Phinehas, son of Eli": ["Duplicate Card"],
    "Phinehas, the Useless": ["Duplicate Card"],
    "Phinehas, the Zealous": ["Duplicate Card"],
    "Piety of Mary": ["False Religious Practice"],
    "Plague of Boils": ["Plague"],
    "Plagued Congregation": ["Gender"],
    "Plunderers": ["Generic Character"],
    "Potiphar": ["Duplicate Card"],
    "Prince of the Air": ["Demon"],
    "Prisoner at Gaza": ["Generic Character"],
    "Prophecy of Eldad & Medad": ["Based on Prophecy"],
    "Prophets of Baal": ["Generic Character"],
    "Prophets of Samaria": ["Generic Character"],
    "Proud Pharisee": ["Generic Character"],
    "Providing Angel": ["Angel"],
    "Que": ["Demon"],
    "Queen Maachah": ["Duplicate Card"],
    "Queen of Sheba": ["Duplicate Card"],
    "Rahab": ["Canaanite"],
    "Rahab, the Promised": ["Canaanite"],
    "Rapha of Gath": ["Giant"],
    "Reassuring Angel (Ap)": ["Angel"],
    "Rebellious": ["Demon"],
    "Rebellious Israelites": ["Generic Character"],
    "Rebellious Spirit": ["Demon"],
    "Recruiting Officer": ["Generic Character"],
    "Reuben": ["Duplicate Card"],
    "Reuben, the Preeminent": ["Duplicate Card"],
    "Righteous Seeker": ["Generic Character"],
    "Rome": ["Church"],
    "Sabbath Breaker": ["Generic Character"],
    "Sabbath Breaker [Black/Gray]": ["Generic Character"],
    "Sabbath Breaker [Brown/Gray]": ["Generic Character"],
    "Sabbath Breaker [Crimson/Gray]": ["Generic Character"],
    "Sabbath Breaker [Gray/Orange]": ["Generic Character"],
    "Sabbath Breaker [Gray/Pale Green]": ["Generic Character"],
    "Samuel, Born of Prayer": ["Duplicate Card"],
    "Scapegoat": ["Animal"],
    "Scapegoat (PoC)": ["Animal"],
    "Scattered": ["Canaanite"],
    "Scraps Under the Table": ["Canaanite"],
    "Scribe": ["Generic Character"],
    "Seeker of the Lost": ["Generic Character"],
    "Seizing Spirit": ["Demon"],
    "Selfish Kinsman": ["Generic Character"],
    "Seraph": ["Angel"],
    "Seraph with a Live Coal": ["Angel"],
    "Servant Angel": ["Generic Character"],
    "Servant Girl": ["Duplicate Card"],
    "Servants by the River": ["Angel"],
    "Seven Wicked Spirits": ["Demon"],
    "Shammah, the Hararite": ["Duplicate Card"],
    "Sheba": ["Duplicate Card"],
    "Shield of Faith (Ki)": ["Depicting a Weapon"],
    "Shobach": ["Duplicate Card"],
    "Sibbechai (Pi)": ["Giant"],
    "Silly Women": ["Generic Character"],
    "Simeon, the Vengeful": ["Duplicate Card"],
    "Sisera": ["Canaanite", "Duplicate Card"],
    "Sodom": ["Canaanite"],
    "Sodom & Gomorrah": ["Canaanite"],
    "Soldiers of Zobah": ["Generic Character"],
    "Sower": ["Generic Character"],
    "Spear of Joshua (Wa)": ["Fought in an Earthly Battle"],
    "Spies at Ai": ["Generic Character"],
    "Spirit of Doubt": ["Demon"],
    "Spirit of Fear": ["Demon"],
    "Spiritual Gifts": ["Spiritual Gifts"],
    "Spy": ["Generic Character"],
    "Stone Carriers": ["Generic Character"],
    "Stricken": ["Duplicate Card"],
    "Struck & Scattered": ["Canaanite"],
    "Stubborn Heifer": ["Animal", "Generic Character"],
    "Suicidal Swine Stampede": ["Animal"],
    "Swift": ["Angel"],
    "Syrian Archer": ["Generic Character"],
    "Syrian Mercenaries": ["Generic Character"],
    "Tekoan Woman": ["Generic Character"],
    "Temple Priests": ["Generic Character"],
    "Temptation": ["Demon"],
    "Tenants Kill the Son": ["Pharisee"],
    "The Angel Under the Oak": ["Angel"],
    "The Angel of His Presence (PoC)": ["Angel"],
    "The Angel of the Winds": ["Angel"],
    "The Clashing King": ["Canaanite"],
    "The Crafty Gibeonites": ["Canaanite"],
    "The Defender of the Saints": ["Angel"],
    "The Destroyer": ["Angel"],
    "The Destroyer (PoC)": ["Plague"],
    "The Ephesian Mentor": ["Duplicate Card"],
    "The Faithful Leaders": ["Church"],
    "The Fallen Star": ["Demon"],
    "The Five Kings": ["Canaanite"],
    "The Foretelling Angel (PC)": ["Angel"],
    "The Great Fish": ["Animal"],
    "The Ram in the Thicket": ["Animal"],
    "The Serpent": ["Animal"],
    "The Tabernacle": ["Duplicate Card"],
    "The Thief": ["Demon"],
    "The Three Visitors": ["Angel"],
    "The Twelve-Fingered Giant": ["Giant"],
    "The Victorious Being": ["Angel"],
    "The Woman of Thebez": ["Duplicate Card"],
    "The god of this World": ["Demon"],
    "Tower of Thebez": ["Canaanite"],
    "Transgressors": ["Generic Character"],
    "Trembling Demon": ["Demon"],
    "Unfaithful Priests": ["Generic Character"],
    "Uriah the Hittite": ["Canaanite"],
    "Uzzah": ["Duplicate Card"],
    "Valiant Moabites": ["Generic Character"],
    "Valiant Warrior": ["Generic Character"],
    "Wandering Israelites": ["Gender"],
    "War Officer": ["Generic Character"],
    "Warrior in Training": ["Generic Character"],
    "Watcher": ["Angel"],
    "Watchful Servant": ["Generic Character"],
    "Wayward Sheep": ["Animal"],
    "What Will You Do?": ["Canaanite"],
    "Wicked Community": ["Gender"],
    "Wicked Thief": ["Duplicate Card"],
    "Wild Animals": ["Generic Character"],
    "Wild Beast": ["Animal"],
    "Winds": ["Angel"],
    "Withered Hand": ["Generic Character"],
    "Wizard (PC)": ["Generic Character"],
    "Wizards": ["Generic Character"],
    "Woman of Thebez": ["Canaanite"],
    "Woman of Wisdom": ["Generic Character"],
    "Women as Snares": ["Generic Character"],
    "Workers with Familiar Spirits": ["Generic Character"],
    "Worldly Woman": ["Generic Character"],
    "Worshipper of False Gods": ["Depicting an Idol"],
    "Worshipping Demons": ["Depicting an Evil Altar"],
    "Zaccheus": ["Duplicate Card"],
    "Zadok": ["Duplicate Card"],
    "Zadok, Ark Carrier": ["Duplicate Card"],
    "Zebul, the Fraud": ["Canaanite"],
    "Zebulun": ["Duplicate Card"],
    "Zebulun, the Steadfast": ["Duplicate Card"],
    "Zechariah, the Renewer": ["Duplicate Card"],
    "Zecharias, Father of John": ["Duplicate Card"],
    "Zerubbabel": ["Duplicate Card"],
}
