ORDIR_CATEGORY_CARD_MAP = {
    "Acts 12 Card": ["Angel of Deliverance (Ap", "Angel of the Lord (A", "B", "EC)", "Eaten by", "I", "P-2018)"],
    "Acts 19 Card": ["Burning of Magic Books", "Defiant", "Demetrius the Silversmith", "EC)", "Evil Strength (J", "Wa"],
    "Acts Card": ["Agabus (Pr", "Ananias of Damascus (Ap", "Angel of Deliverance (Ap", "Angel of the Lord (A", "Angelic Visit", "Antidote", "B", "Bless the Nations", "Blinding Light", "E", "EC)", "P-2017", "P-2018)", "PC)"],
    "Animal": ["Bear", "Beasts of the Earth", "Behemoth", "Coliseum Lion"],
    "Antediluvian": ["Abel (C", "Adam", "Adam (Man)", "Adam (Pa", "CW)", "FM)", "Pi", "the Exile"],
    "Armor of God Enhancement": ["B", "Belt of Truth (Wa", "Breastplate of Righteousness (A", "Ki", "PC)", "Wa"],
    "Assyrian": ["Assyrian Ambassador", "Assyrian Archer (FF", "Assyrian Camp", "LR)", "Ninevites", "The King of Nineveh"],
    "Assyrian Site": ["Halah", "Nineveh", "•    Assyria"],
    "Babylonian": ["Arioch", "Ashpenaz", "Astrologers (Pr", "Babylon the Great", "LR)", "Nebuchadnezzar", "TP"],
    "Babylonian Site": ["Babylonian Banquet Hall", "RJ)", "•    Babylon (Wo"],
    "Based on Prophecy": ["Book of Nathan", "Prophecy of Eldad & Medad"],
    "Beast": ["Bear", "Beast from the Earth (Or", "Beast from the Sea (Or", "RJ)", "Wa"],
    "Bows, Arrows, Spears, Javelins and Darts": ["Abishai's Spear (Ki", "Adino's Spear (Wa", "Arrow of Deliverance", "II)", "Ki"],
    "Canaanite": ["Ahimelek the Hittite", "Ishmaiah the Gibeonite", "King Hiram (FF"],
    "Canaanite Site": ["FM)", "Hebron", "Hormah", "Jericho", "Pit of Dothan (Wo", "•    Canaan"],
    "Cloud Card": ["Abed-nego (Azariah)", "Abel", "Abraham", "Amram & Jochebed"],
    "Connected with Demons": ["Mary Magdalene"],
    "Daniel Card": [""Covenant Breakers"]", "Abed-nego (Azariah)", "Abednego (Azariah)", "CW", "Daniel (Pr", "Daniel's Prayer", "Faith Unbowed", "Lost Soul [Daniel", "Lost Soul [Daniel 9:5", "Michael's Sword", "P)", "P-2023 Hebrew)", "Son of God (K", "Stone Cut"],
    "Deacon": ["EC)", "Nicanor (EC", "Nicolas of Antioch (EC", "P)", "Parmenas (H", "Philip the"],
    "Demon": ["Abaddon the Destroyer (Or", "Admiral", "Afflicting Spirit", "Bear", "RJ)"],
    "Depicting a Weapon": ["Book of the Wars", "Shield of Faith"],
    "Deuteronomy Card": [""Covet"]", "Balaam", "Blessings for Obedience", "Courage (B", "Covenant of Palestine (Pa", "Doomed Canaanites", "Doubt", "Doubt (Pi", "Emim", "Enchanter", "Israel's Rebellion", "Ki)", "LC)", "Lost Soul [Deuteronomy", "Lost Soul [Deuteronomy 5:21", "Or"],
    "Disciple": ["Andrew", "Ap)", "First Called", "Fisher of Men", "•    Andrew (I"],
    "Disease": ["All Hope Lost", "Boils (B", "C", "Eaten by Worms", "Infectious Disease", "Lacking Sleep", "Or", "Sowing the Seed", "Wa)"],
    "Edomite": ["Basemath", "Charioteers of Seir", "David's Servants", "Doeg (A", "Or"],
    "Egyptian Site": ["Egypt (H", "Pharaoh's Court", "Pharaoh's Prison", "PoC)", "Wo", "•    Banks of the Nile"],
    "Empty Tomb Hero": ["Angel at Tomb", "Di)", "Joanna", "Joanna (Wo", "the Generous", "•    Angel at the Tomb"],
    "Ephesians Card": ["B", "Barrels]", "Belt of Truth (Wa", "Breastplate of Righteousness (A", "D", "G)", "Ki", "Lost Soul [Ephesian 5:14", "Lost Soul [Ephesians 5:14] (A", "Music Leader (PC", "Obsidian Minion [Black]", "Obsidian Minion [Gold", "P)", "PC)", "Soldier of God", "Wa"],
    "Esther Card": ["Courage of Esther", "Esther", "Esther (B", "Hadassah (Esther)", "Haman's Boasting", "Haman's Gallows", "Haman's Plot (Pa", "Haman's Plot Exposed", "Irrational Rage", "Or)", "RR)", "the Courageous"],
    "Exodus Card": ["Aaron", "Aaron (G", "Aaron's Rod (A", "Antidote", "Burning", "Burning Bush (L", "C", "Di)", "G", "God's Mediator", "Moses' Brother", "Or)", "Pa", "Pa)", "Pi"],
    "Ezekiel Card": [""Shuffler"]", "Baggage", "Charred Vine", "Cherubim (Wa", "Drawn Sword", "Ezekiel", "Ezekiel (Pr", "Ezekiel's Stick (B-L", "FF2", "FF2)", "God Strengthens", "LR", "Lost Soul [Ezekiel 13:18] (H", "Lost Soul [Ezekiel 31:14", "Pi", "RR)", "Vain Vision", "Valley of Dry Bones", "Wo)"],
    "Ezra Card": [""Accusers"]", "Cymbals of the Levites (RA", "Ezra", "Ezra's Journey", "Favored by God", "Feast of Atonement", "Jeshua", "LC)", "Lost Soul [Ezra 4:6", "Oath of Purity", "RR)", "Zerubbabel", "Zerubbabel's Temple (FF", "the Restorer"],
    "Feast": ["Day of Atonement", "Feast of Atonement", "Feast of Booths (Pi", "LC)"],
    "Flood Survivor": ["Ham", "Ham's Wife", "Japheth", "Japheth's Wife", "Noah"],
    "Fool": ["Ambushed Moabites", "Conspiring Herodians", "Conspiring Servants"],
    "Fruit of the Spirit": ["EC)", "Faithfulness", "Gentleness (Or", "Goodness (Or", "Joy (Or"],
    "Gender": ["Boaz' Reapers", "Bride of Christ", "Citizens of Sychar", "Every Tribe"],
    "Generic Character": ["Abusive Soldiers", "Abusive Taskmaster", "Afflicting", "Angel at", "Angel at Bethesda", "Angel at Jerusalem (Wa", "Captive Princes", "Man with Withered Hand", "Pharaoh's", "Pi", "RR)", "•    Abram's Army", "•    Absalom's Soldiers", "•    Blood Avenger"],
    "Genesis 1-7 Enhancement": ["Abel's Sacrifice", "Construction Begins", "Covenant of Eden (Pa", "PoC)"],
    "Genesis 12-24 Hero": ["Abraham (P", "Abram", "Abram's Army", "CW)", "the Blameless"],
    "Genesis 3 Curse": ["Cursed Ground", "Serpent's Curse", "The Fall of", "•    Birthing Pains"],
    "Genesis 37-50 Card": [""Famine"]", "Asher", "Benjamin", "Brother's Reunion", "Brought to Egypt", "Buying Grain", "Coat of", "Lost Soul [Genesis 45:6", "Lost Soul [Genesis 47:17", "Out of Their Hands", "the Rich", "the Young"],
    "Genesis Card": [""Wicked"]", "A New Beginning", "A Wife for Isaac", "Abel (C", "Abel's Sacrifice", "Abraham (Pa", "Abram", "CW)", "Lost Soul [Genesis 45:6", "Lost Soul [Genesis 6:5", "Out of Their Hands", "Pi", "the Blameless"],
    "Giant": ["Ahiman", "Arba", "Emim", "Goliath", "Greatest Anakim", "Son of Anak"],
    "Giant Slayer": ["Abishai", "Abishai (K", "Caleb", "Caleb (FF", "Chief of Thirty", "FM", "Ki)", "P)", "Wa"],
    "Greek": ["Alexander of Troas", "Alexander the Great", "Antiochus IV Epiphanes", "EC)", "Nicolas of Antioch (P", "Titus", "Titus (Ap", "the Messenger"],
    "Haggai Card": ["Haggai (FF", "PoC)"],
    "Heavenly Temple Artifact": ["Ki", "P)", "RJ", "The Book of Life", "The Golden Altar", "•    Ark of the Covenant (Wa"],
    "Hebrews Card": [""Slaves"]", "CW)", "Dutiful Priest", "Entertaining Angels (Ap", "Equipped for the Mission", "Eternal", "Falling Away (Wo", "Lost Soul [Hebrews 2:15", "Lost Soul [Hebrews 4:13", "P)", "The Angel of the Winds (CW", "The Faithful Leaders", "The Second Coming (CW"],
    "Herod": ["Ap", "Archelaus (Ap", "Di)", "EC", "GC)", "Herod Agrippa I (G", "Herod Archelaus"],
    "Herod in the Title": ["Altar of Incense (E", "Golden Cherubim", "Holy", "Pi)", "•    Altar of Burnt Offering (L"],
    "High Priest": ["Aaron", "Aaron (G", "Di)", "God's Mediator", "Moses' Brother", "Pa", "Pi"],
    "House of Eleazar": ["Ahimaaz", "Ahimaaz (Ki", "Amariah the High Priest", "FM)", "Pi", "the Swift"],
    "House of Ithamar": ["Abiathar", "Abiathar (K", "Ahimelech", "Chief Priest", "Pi)", "the Survivor"],
    "I Chronicles Card": ["Abiezer (Wa", "Abishai (Wa", "Amasai the Raider", "Asaph", "Book of Gad the Seer", "Book of Nathan", "Bronze Cymbals", "Ki)", "Musicians' Chambers", "Stronghold in the Desert"],
    "I Samuel Card": [""Fat"]", "Abiathar", "Abiathar (K", "Abigail (K", "Abishai", "Called to Prophesy", "Lord of Armies", "Lost", "Lost Soul [I Samuel 2:23]", "Lost Soul [I Samuel 2:29", "Pi)", "RA2)", "Warrior Overtaken", "Wo", "the Survivor"],
    "I Thessalonians Card": ["In the Clouds", "Letters to the Thessalonians", "Work with Your Hands"],
    "II Chronicles 17-20 Hero": ["Amariah", "Amariah the High Priest", "Elishama the", "the High Priest"],
    "II Chronicles 26 Enhancement": ["Acts of Uzziah", "Body Armor", "Break Down the Wall of Gath"],
    "II Chronicles 29-32 Hero": ["Angel at Jerusalem (Wa", "Azariah the High Priest", "Pi", "RR)"],
    "II Chronicles Card": [""*/4"]", "Abijah", "Acts of Uzziah", "Amariah", "Amariah the High Priest", "Appointing Judges", "Body Armor", "Book of Hozai", "Glory of the Lord (Ki", "Led Astray", "Lost Soul [II Chronicles 15:4", "Lost Soul [II Chronicles 16:10", "P)", "the Conqueror", "the High"],
    "II Kings Card": ["Altar of Ahaz", "Amaziah", "Assyria's Tribute", "Azariah", "Book of the Law (Pi", "Chariot of Fire", "Destruction of Nehushtan", "Elisha (Pr", "Hezekiah", "LC", "P)", "PoC)", "the Just", "the Strong"],
    "II Samuel 14-17 Evil Character": ["Ahimaaz (Ki", "Hushai (A", "Ittai (Wa", "Ki)", "Or)", "Pi)", "Tekoan Woman"],
    "II Samuel 14-18 Evil Character": ["Ahimaaz", "Ahimaaz (Ki", "FM)", "Hushai (A", "Ittai (Wa", "Ki)", "Or)", "Pi", "the Swift"],
    "II Samuel Card": [""Banished"]", "Abiezer", "Abishai", "Abishai's Spear (Ki", "Adino (Or", "Adino's Spear (Wa", "Benaiah Snatches a Spear", "Chief of Thirty", "II)", "Ki", "Ki)", "Lost Soul [II Samuel 14:13", "Lost Soul [II Samuel 23:6]", "the Anathothite"],
    "II Thessalonians Card": ["Ki)", "Might of Angels (Wa", "Stand Firm"],
    "Idol": ["Altar of Dagon (Pa", "Asherah Pole (Ki", "FM)", "Gideon's Ephod", "LC)"],
    "Isaiah 6 Enhancement": ["FF2", "Forcefulness of Isaiah", "Isaiah's Call", "LR)", "Live Coal (Pr"],
    "Isaiah Card": ["Angel of His Presence", "Bearing Our Sin", "By His Wounds", "Confused", "Covenant Keepers (Pi", "Eyes to See", "FF2)", "Isaiah (Pr", "RR)"],
    "James Card": [""Demon Shuffle"]", "Endurance of Job", "Enticed", "James", "Leader in Jerusalem", "Lost Soul [James 1:15", "Lost Soul [James 4:6", "Mask of Worldliness (AW", "Mercy of James (Or", "PC)", "RR)", "Seeds of Doubt", "Trembling Demon (FF"],
    "Jeremiah Card": [""Shame"] (RA", "Balm of Gilead (B", "Battle Axe (Or", "Buckler", "Compassion of Jeremiah", "D", "Hope Bringer", "Iron", "Jeremiah", "Jeremiah (D", "Ki)", "LR)", "Lost Soul [Jeremiah 3:25", "Lost Soul [Jeremiah 7:18", "Or)", "Pi", "Pr", "TP)", "Wa"],
    "Job Card": [""Blind"]", ""Vindicated"]", "Behemoth", "Bildad", "Day of Fury", "Eliphaz", "Endurance of Job", "Job", "Job (Pi", "Job Overcomes", "Job's", "Lost Soul [Job 13:18", "Lost Soul [Job 29:15", "P)", "the Perseverant", "the Shuhite", "the Temanite"],
    "John Card": ["A New Commandment", "Andrew", "Angel at Bethesda", "Behold the Lamb", "Bread of Life", "First Called", "Fisher of Men"],
    "Jonah Card": ["Chastisement of the Lord (Or", "God's Mercy", "Jonah (Pr", "Nineveh", "Ninevites", "Ninevites Repent", "P", "Pagan Sailors", "PoC)", "The Great Fish", "The King of"],
    "Joshua Card": ["Ambush", "Ambush the City (Ki", "Ark of the Covenant", "Army of the Lord (Pi", "Battle Cry", "Caleb", "Caleb (FF", "Captain of the Host (Wa", "Deceitful Possessions", "FM", "II)", "Ki", "P)", "Pi)", "RR)", "Ram's Horn (Wa", "The Long Day", "the Rewarded"],
    "Judge": ["Abdon", "Deborah", "Deborah (A", "Or", "PoC)", "the", "the Brave"],
    "Judges Card": [""Hormah"]", "Abdon", "Angel with the Secret Name (Wa", "Army of Simeonites", "Forced Labor", "Lost Soul [Judges 1:17", "Lost Soul [Judges 3:30", "RA2)"],
    "King": ["Abijah", "Amaziah", "Asa", "the Blameless", "the Conqueror", "the Just"],
    "King of Israel": ["David", "David [Green] (Wa", "David [Red] (Wa", "Giant Slayer (K", "Ki", "Ki)", "P)", "RR)"],
    "King or Queen of Judah": ["Abigail (K", "Abijah", "Amaziah", "RA2)", "Wo", "the Conqueror", "the Just"],
    "Lamentations Card": ["Cup of Wrath", "Desolate Gateways", "Hunger (Pr", "Lamenting", "RR)"],
    "Leviticus Card": ["Aaron", "Abihu", "Burnt Offering (Pi", "Canaan", "Day of Atonement", "Eleazar", "Feast of", "Feast of Booths", "I Am Holy", "IR)", "Leper", "Mildewed House", "Nadab", "Peacemaker", "son of Aaron", "the Disobedient", "the Wicked"],
    "Lion": ["Coliseum Lion", "Devouring Lion", "Hungry Lion", "Lions"],
    "Luke Card": ["A Child is Born", "Amazing Faith", "An Angel Appears", "Andrew (I", "Angel", "Angel of the Lord (C", "Anna", "Anna (Pr", "Ap)", "Bartholomew", "D", "Di)", "E", "F)", "P-2019 Seasonal", "Son of God (L", "the Widow"],
    "Major or Minor Prophet": ["CW", "Daniel", "Daniel (Belteshazzar)", "Daniel (Pr", "P)", "the"],
    "Mark Card": ["Ap", "Bartimaeus", "Boanerges", "Faith of Bartimaeus", "GC)", "H", "Jairus (GC", "Jairus' Daughter (Wo", "LR)", "Lost Soul [Mark 1:40] (J", "Lost Soul [Mark 7:21-22", "Love of Jesus", "Mary the", "New Covenant", "P)"],
    "Martyr": ["Andrew", "Antipas", "Ap)", "First Called", "Fisher of Men", "•    Andrew (I"],
    "Matthew Card": ["A Roman Soldier's Faith", "Abihud", "Achim", "Alabaster Jar", "Angelic Guidance (I", "Ap)", "P)", "Son of God", "Star of Bethlehem (GC", "The Resurrection", "the Compiler", "the Exilarch", "the Progeny"],
    "Micah Card": ["Assyrian Invaders", "Bethlehem", "Micah (RA", "Out of Bethlehem", "PoC)", "Swords into Plowshares", "Swords to", "The Afflicted", "The Outcasts"],
    "Moabite": ["Ambushed Moabites", "D", "David's Servants", "Eglon's Army", "Emim", "J", "Or)", "Ruth", "Ruth (B", "the Devoted", "the Redeemed"],
    "Musician": ["Asaph", "Barak (Pa", "CW)", "Chenaniah", "the Psalmist", "•    Asaph"],
    "Nativity Card": ["A Child is Born", "An Angel Appears", "Angel of Warning (Ap", "Angel of the Lord (C", "Angelic Guidance (I", "Anna", "Anna (Pr", "Ap)", "D", "Di)", "E", "F)", "LR)", "Son of God", "TP", "the Widow"],
    "Nehemiah Card": ["Baruch", "Builder's Spear", "Builder's Sword", "Determination of Nehemiah", "Dust", "Eliashib the High Priest", "Forbidden Marriage", "I Am Sustainer", "Jaddua", "Jerusalem Tower (Pa", "P)", "RR)", "Rubble", "Son of Zabbai", "Wall of Protection (LC", "son of"],
    "Numbers Card": ["Angel in the Path (Wa", "Angel's Sword", "Ark of the Covenant (Wa", "Blue Tassels (Pa", "Book of the Wars", "Brass Serpent", "Brass Serpent (Or", "Covenant of", "Dreamers", "Eldad", "Eleazar", "Forty Years", "Ki)", "P)", "Pi", "RR)", "Son of"],
    "Patriarch": ["Abraham (Pa", "Abram", "Asher", "CW)", "the Blameless"],
    "Persian": ["Bear", "C", "Esther", "Esther (B", "Hadassah (Esther)", "Haman (B", "King Darius", "Or", "P)", "P-2009", "P-2019)", "the Courageous", "the Mede"],
    "Persian Site": ["Lions' Den", "•    Lion's Den"],
    "Pharaoh": ["D", "H", "King Shishak", "King So", "Or)", "Pharaoh (A", "Pharaoh Hophra"],
    "Philistine": ["Abimelech", "Ahuzzath", "Commander Phicol", "Ittai (Wa", "Ki)", "King of Gerar", "Obed-Edom the Gittite"],
    "Plague": ["Death of Firstborn (Pa", "Plague of Blood (Pa", "Plague of Boils (G", "PoC)"],
    "Poison": ["Bad Figs (Pr", "D", "FM)", "Fiery Serpents (Wa", "Or", "Poison (B", "Poison of", "Wa)"],
    "Postexilic": ["Abihud", "Achim", "the Compiler", "the Exilarch", "the Progeny"],
    "Priest": ["Aaron", "Aaron (G", "Di)", "God's Mediator", "Moses' Brother", "Pa", "Pi"],
    "Priestly Artifact": ["Pi)", "Priestly Breastplate (C", "Priestly Crown", "RR)", "The Silver", "•    Blue Tassels (Pa"],
    "Prophet": ["Aaron", "Balaam", "Caiaphas the Conspirator", "Di", "Di)", "God's Mediator", "LR)", "Moses' Brother", "Pa", "Pi", "Son of Beor", "•    Aaron (G", "•    Balaam (Pr"],
    "Revelation 12-19 Evil Character": ["Babylon the Great", "Beast from the Earth (Or", "Beast from the Sea", "RJ)", "Wa"],
    "Revelation Angel": ["Angel from the Altar", "Angel from the Sun", "Angel of Might"],
    "Revelation Card": ["A Mighty Blow", "Angel from the Altar", "Angel from the Sun", "Angel of Might", "Blood of the Lamb (H", "Burning Censer (C", "GC", "Grapes of Wrath (TP", "New Jerusalem (IJ+", "P)", "P-2019 Winner", "RJ)", "Wa"],
    "Roman": ["Aquila (Ap", "Centurion", "Claudia", "Claudia (Wo", "EC)", "PC)", "the Hospitable"],
    "Roman Centurion": ["C", "Centurion", "Cornelius (A", "EC)", "GC)", "Or", "The Centurion at Calvary (Di"],
    "Roman Emperor": ["EC", "Emperor", "Emperor Augustus (RR", "Emperor Caius Caligula (Ap", "P)", "RR)"],
    "Roman Governor": ["Antonius Felix", "Di", "Governor Felix", "P)", "Pontius Pilate (Ap", "Quirinius"],
    "Roman Site or Fortress": ["Coliseum", "Nero's Realm (Ap", "PC)", "Pi)", "Roman Prison (C", "Rome"],
    "Roman Soldier": ["C", "Centurion", "Cornelius (A", "EC)", "GC)", "Or", "The Centurion at Calvary (Di"],
    "Royalty (or Royal or Member of a Royal Family)": ["Abigail (K", "Abijah", "Amaziah", "RA2)", "Wo", "the Conqueror", "the Just"],
    "Ruth Card": ["Abeyance", "Amminadab", "Best Friends", "Bethlehem", "Boaz (J", "Boaz' Offspring", "Boaz' Resolve", "Boaz' Sandal", "Land of Moab", "Marriage Covenant", "Pa)", "Threshing Floor", "the Generous", "the Gracious"],
    "Samaritan": ["Citizens of Sychar", "Good Samaritan", "The", "The Good Samaritan"],
    "Scholar or Philosopher in the Title": ["Amariah", "Amariah the High Priest", "Azariah the", "the High Priest"],
    "Son of Jacob": ["Asher", "Benjamin", "the Rich", "the Young"],
    "Spiritual Gifts": ["Spiritual Gifts"],
    "Star Card": ["A Royal Priesthood", "Aaron", "Abihud", "Abraham's Descendant", "Achim", "Amazing Faith", "Brass Serpent", "God's Mediator", "Jacob's Ladder", "Manna", "Matthew's", "P)", "Star of Bethlehem (GC", "the Compiler", "the Progeny"],
    "Syrian": ["God's Choice", "Leah", "Leah (Wo", "Rachel", "TP)", "Weary-Eyed"],
    "Tabernacle Artifact": ["Altar of Burnt Offering (L", "Altar of Incense (E", "Ark of the", "Pi)", "•    Aaron's Staff"],
    "Tabernacle Priest": ["Aaron", "Aaron (G", "Di)", "God's Mediator", "Moses' Brother", "Pa", "Pi"],
    "Temple Artifact": ["Altar of Burnt Offering (L", "Altar of Incense (E", "Ark of the", "Pi)", "•    Aaron's Staff"],
    "Temple Priest": ["Amariah", "Amariah the High Priest", "Azariah the", "the High Priest"],
    "Thief": ["Barabbas (Pi", "Concealed Canaanites", "Fence", "GC)", "•    Ambushing Bandits"],
    "Wilderness Character": ["Aaron", "Aaron (G", "Di)", "God's Mediator", "Moses' Brother", "Pa", "Pi"],
    "Zechariah Card": ["A Royal Priesthood", "Altar of Incense (E", "Book of the Covenant (P", "Bow of Battle", "By My Spirit", "Eliashib the High Priest", "Ezra", "Favored by God", "Golden", "Jaddua", "Joshua the High Priest (Pi", "LR)", "Messenger Angel", "Mighty Men", "Pi)", "The Flying Scroll", "•    Altar of Burnt Offering (L"],
}
