# ORDIR reference mapping
ORDIR_REFERENCE_ENTRIES = {
    ("111 Washing Hands", "Di"): ["Roman"],
    ("A Royal Priesthood", "PoC"): ["High Priest", "King or Queen of Judah"],
    ("Abducted Subjects", "LC"): ["Edomite"],
    ("Access Denied", "II"): ["Edomite"],
    ("Achaicus", "EC"): ["Corinth Church"],
    ("Alexandrian Ship", "PC"): ["Roman Centurion"],
    ("Altar of Burnt Offering", "Pi"): ["Offering"],
    ("Amaziah the Ungodly Priest", "Pi"): ["King of Israel"],
    ("Amos", "PoC"): ["King of Israel"],
    ("Angelic Visitor", "EC"): ["Roman Centurion"],
    ("Annas the Elder", "GC"): ["Sadducee"],
    ("Aquila", "EC"): ["Missionary"],
    ("Archippus", "PC"): ["Colossae Church"],
    ("Army of Jericho", "CW"): ["Canaanite Site"],
    ("Arrest in Gethsemane", "Di"): ["Sadducee"],
    ("Avoiding Edom", "II"): ["Edomite"],
    ("Barabbas", "Pi"): ["Sadducee"],
    ("Barnabas", "EC"): ["Sadducee"],
    ("Bear", "PoC"): ["Persian"],
    ("Bear", "RA"): ["Persian"],
    ("Begrudging King", "II"): ["Edomite"],
    ("Bereans", "EC"): ["Missionary"],
    ("Breaking Jerusalems Wall", "Ki"): ["King of Israel"],
    ("Breaking Jerusalems Wall", "RA2"): ["King of Israel", "Temple Artifact"],
    ("Brood of Vipers", "GC"): ["Sadducee"],
    ("Burning of Magic Books", "EC"): ["Ephesus Church", "Missionary"],
    ("Burnt Offering", "IR"): ["Offering"],
    ("Burnt Offering", "Pi"): ["Offering"],
    ("Caiaphas the Conspirator", "GC"): ["Sadducee"],
    ("Canaan the Cursed", "FM"): ["Canaanite Site"],
    ("Canaanite Wives", "FM"): ["Canaanite Site"],
    ("Captain of the Chariots", "LC"): ["Syrian"],
    ("Captain of the Guard", "GC"): ["Sadducee"],
    ("Cast into Lions Den", "PC"): ["Persian"],
    ("Centurion at Calvary", "GC"): ["Roman"],
    ("Centurion at Capernaum", "GC"): ["Roman"],
    ("Centurion at Jerusalem", "PC"): ["Roman"],
    ("Chemosh Worship", "FM"): ["Moabite"],
    ("Chief Priests", "RJ"): ["Sadducee"],
    ("Chief Priests Offer", "Di"): ["Sadducee"],
    ("Child of Great Wisdom", "Ap"): ["Sadducee"],
    ("Chloe", "EC"): ["Corinth Church"],
    ("Chronicles of the Kings", "LC"): ["Temple Artifact"],
    ("City of Refuge", "Pi"): ["High Priest"],
    ("Claudius Lysias", "PC"): ["Roman", "Roman Soldier"],
    ("Clement", "PC"): ["Philippi Church"],
    ("Commitment of Paul", "EC"): ["Corinth Church"],
    ("Covenant with Phinehas", "Pi"): ["House of Eleazar"],
    ("Crispus", "EC"): ["Corinth Church"],
    ("Damascus", "EC"): ["Syrian"],
    ("Dance of Death", "GC"): ["Herod"],
    ("Davids Servants", "FM"): ["Moabite"],
    ("Davids Servants", "II"): ["Edomite"],
    ("Day of Atonement", "Pi"): ["Offering"],
    ("Defenestrated!", "RA2"): ["King of Israel"],
    ("Denarius", "Di"): ["Roman", "Roman Emperor", "Roman Governor"],
    ("Denarius", "IJ+"): ["Roman", "Roman Emperor"],
    ("Destruction of Nehushtan", "PoC"): ["Temple Artifact"],
    ("Doctrine Like Leaven", "RA"): ["Sadducee"],
    ("Doeg the Slaughterer", "II"): ["Edomite"],
    ("Doegs Slaughter", "Pi"): ["House of Ithamar"],
    ("Doomed Conspirators", "PC"): ["Missionary", "Mob"],
    ("Dutiful Priest", "CW"): ["Offering"],
    ("Edomite Camp", "LC"): ["Edomite"],
    ("Edomite Captors", "LC"): ["Edomite"],
    ("Edomite Rebellion", "LC"): ["Edomite"],
    ("Eglons Army", "II"): ["Moabite"],
    ("Egyptian Rebel", "PC"): ["High Priest", "Roman"],
    ("Emim", "FM"): ["Moabite"],
    ("Emperor Augustus", "RR"): ["Roman"],
    ("Emperor Caius Caligula", "RR"): ["Roman"],
    ("Emperor Nero", "P"): ["Roman Soldier"],
    ("Emperor Vitellius", "RR"): ["Roman"],
    ("Emphatic Incriminators", "GC"): ["Sadducee"],
    ("Ends of the Earth", "RJ"): ["Missionary"],
    ("Enemies to the South", "II"): ["Edomite"],
    ("Epaphras", "PC"): ["Colossae Church"],
    ("Epaphroditus", "PC"): ["Missionary"],
    ("Ephesian Elders", "PC"): ["Ephesus Church"],
    ("Ephesian Mentor", "PC"): ["Ephesus Church"],
    ("Ephesian Widow", "PC"): ["Ephesus Church"],
    ("Esau the Hunter", "LR"): ["Edomite"],
    ("Esau the Hunter", "P"): ["Edomite"],
    ("Esaus Land", "II"): ["Edomite"],
    ("Ethiopian Treasurer", "EC"): ["Deacon"],
    ("Euodia", "PC"): ["Philippi Church"],
    ("Evicted", "CW"): ["Pharaoh"],
    ("Expelling the Jews", "FF"): ["Roman", "Roman Emperor"],
    ("Faithful Priest", "EC"): ["Jerusalem Church"],
    ("False Accusations", "GC"): ["Sadducee"],
    ("False Witnesses", "G"): ["Sadducee"],
    ("False Witnesses", "RR"): ["Sadducee"],
    ("Famished", "IR"): ["Pharaoh"],
    ("Fellowship Offering", "Pi"): ["Offering"],
    ("Filling Zerubbabels Temple", "FF"): ["Temple Artifact"],
    ("First Fruits", "Pi"): ["Offering"],
    ("Fortify Site", "RA2"): ["Canaanite Site"],
    ("Fortunatus", "EC"): ["Corinth Church"],
    ("Gamaliel", "Ap"): ["Sadducee"],
    ("Gates of Jerusalem", "LC"): ["King or Queen of Judah"],
    ("Gates of Jerusalem", "P"): ["King or Queen of Judah"],
    ("Gates of Samaria", "RA2"): ["King of Israel"],
    ("Gathering the Sanhedrin", "GC"): ["Sadducee"],
    ("Generous Givers", "PC"): ["Missionary", "Philippi Church", "Thessalonica Church"],
    ("Gifts and 99 Offerings", "CW"): ["Offering"],
    ("Gifts and Offerings", "CW"): ["High Priest"],
    ("Glory of the Lord", "P"): ["Temple Artifact"],
    ("Goat with Horn", "Di"): ["Persian"],
    ("Grain Offering", "IR"): ["Offering"],
    ("Grain Offering", "Pi"): ["Offering"],
    ("Great Dread", "II"): ["Moabite"],
    ("Guilt Offering", "IR"): ["Offering"],
    ("Guilt Offering", "Pi"): ["Offering"],
    ("Hadad the Exiled", "LC"): ["Edomite"],
    ("Haggai", "FF"): ["High Priest"],
    ("Haggai", "PoC"): ["Persian"],
    ("Haman", "P-2019"): ["Persian"],
    ("Hamans Boasting", "PoC"): ["Persian"],
    ("Hamans Gallows", "Di"): ["Persian"],
    ("Heavy Taxes", "FF"): ["Roman Emperor"],
    ("Heavy Taxes", "RR"): ["Roman Emperor"],
    ("Herod Agrippa II", "LR"): ["Sadducee"],
    ("Herod Agrippa II", "TP"): ["Sadducee"],
    ("Herod Philip II", "Di"): ["Herod"],
    ("Herod Philip II", "GC"): ["Herod"],
    ("Herod the Great", "GC"): ["Herod"],
    ("Herodians", "GC"): ["Herod"],
    ("Herodias", "GC"): ["Herod"],
    ("Herodias Daughter", "GC"): ["Herod"],
    ("Herods Banquet", "GC"): ["Herod"],
    ("Herods Dungeon", "TP"): ["Herod"],
    ("Herods Executioner", "GC"): ["Herod"],
    ("Herods Guard", "GC"): ["Herod"],
    ("Herods Praetorium", "PC"): ["Herod"],
    ("Herods Treachery", "GC"): ["Herod"],
    ("Herods Treachery", "TP"): ["Herod"],
    ("High Priest Ananias", "RJ"): ["Sadducee"],
    ("High Priest Annas", "Ap"): ["Sadducee"],
    ("High Priest Annas", "Pi"): ["Sadducee"],
    ("High Priest Caiaphas", "Pi"): ["Sadducee"],
    ("High Priests Palace", "GC"): ["Sadducee"],
    ("High Priests Palace", "Pi"): ["Sadducee"],
    ("High Priests Plot", "Pi"): ["Sadducee"],
    ("Honor Thy Enemy", "PoC"): ["Persian"],
    ("Hooked and Shackled", "LC"): ["King or Queen of Judah"],
    ("Hosea", "PoC"): ["King of Israel"],
    ("House of Prayer", "PoC"): ["High Priest"],
    ("House of Rimmon", "FF"): ["Syrian"],
    ("Huldah", "PoC"): ["King or Queen of Judah"],
    ("Idol of Chemosh", "II"): ["Moabite"],
    ("Imprisoned", "Di"): ["Herod"],
    ("Inhabitants of Seir", "II"): ["Edomite"],
    ("Irrational Rage", "PoC"): ["Persian"],
    ("Israel Turned Away", "II"): ["Edomite"],
    ("Jacob Disgruntled Subject", "LC"): ["Roman"],
    ("James Leader in Jerusalem", "PC"): ["Jerusalem Church"],
    ("Jason", "EC"): ["Thessalonica Church"],
    ("Jealous Rage", "EC"): ["High Priest"],
    ("Jehoiada the High Priest", "Pi"): ["Temple Artifact"],
    ("Jerusalem", "Ap"): ["High Priest", "Sadducee"],
    ("Joanna", "Di"): ["Herod"],
    ("Joel", "PoC"): ["King or Queen of Judah"],
    ("Joiada Son of Eliashib", "FF"): ["Feast", "Offering"],
    ("Judith", "LC"): ["Edomite"],
    ("Julius the Centurion", "PC"): ["Roman"],
    ("Just a Hireling", "GC"): ["Sadducee"],
    ("Just a Hireling", "RA"): ["Sadducee"],
    ("King Abijam", "RA3"): ["Temple Artifact"],
    ("King Amaziah", "Ki"): ["King of Israel"],
    ("King Amaziah", "RA2"): ["King of Israel"],
    ("King Asnappar", "FF"): ["Syrian"],
    ("King Balak", "FM"): ["Moabite"],
    ("King Belshazzar", "FF2"): ["Temple Artifact"],
    ("King Darius the Mede", "PoC"): ["Persian"],
    ("King Eglon", "FM"): ["Moabite"],
    ("King Hazael", "LC"): ["Syrian"],
    ("King Jehoash", "RA2"): ["Temple Artifact"],
    ("King Mesha", "FM"): ["Moabite"],
    ("King Rezin", "PoC"): ["Syrian"],
    ("King Xerxes", "PoC"): ["Persian"],
    ("King of Edom", "LC"): ["Edomite"],
    ("Kings Signet Ring", "LC"): ["King or Queen of Judah"],
    ("Land of Chemosh", "II"): ["Moabite"],
    ("Land of Moab", "LC"): ["Moabite"],
    ("Letter to the Philippians", "PC"): ["Missionary", "Philippi Church"],
    ("Letters to the Corinthians", "EC"): ["Corinth Church"],
    ("Letters to the Thessalonians", "EC"): ["Thessalonica Church"],
    ("Lions Den", "PoC"): ["Persian"],
    ("Lost Soul", "II"): ["Edomite", "Moabite"],
    ("Lost Soul "Subdued", "II"): ["Moabite"],
    ("Lost Soul "Subdued" Judges 3:30", "II"): ["Moabite"],
    ("Lost Soul "Subdued" [Judges 3:30]", "II"): ["Moabite"],
    ("Lost Soul Judges 3:30", "II"): ["Moabite"],
    ("Lost Soul [Judges 3:30 "Subdued"]", "II"): ["Moabite"],
    ("Lost Soul [Judges 3:30]", "II"): ["Moabite"],
    ("Malachi", "PoC"): ["Persian"],
    ("Malchus", "GC"): ["Sadducee"],
    ("March from Edom", "II"): ["Edomite"],
    ("Mary the Mother of Mark", "EC"): ["Jerusalem Church"],
    ("Massacre of Innocents", "Di"): ["Herod", "Pharaoh"],
    ("Massacre of Innocents", "GC"): ["Herod"],
    ("Men of Moab", "PoC"): ["Moabite"],
    ("Micah", "PoC"): ["King or Queen of Judah"],
    ("Missionary Ship", "EC"): ["Missionary"],
    ("Moab", "FM"): ["Moabite"],
    ("Moabite Army", "FM"): ["Moabite"],
    ("Moabite Marauders", "FM"): ["Moabite"],
    ("Mocking Soldier", "Pi"): ["Roman"],
    ("Naamans Horses", "RR"): ["Syrian"],
    ("Neros Realm", "PC"): ["Roman", "Roman Emperor"],
    ("Nicanor", "EC"): ["Deacon"],
    ("Nicodemus", "Ap"): ["Sadducee"],
    ("Nicodemus", "Di"): ["Sadducee"],
    ("Night Raid", "RR"): ["Syrian"],
    ("No Assembly", "II"): ["Moabite"],
    ("Noblewomen", "EC"): ["Thessalonica Church"],
    ("Not Your Possession", "II"): ["Moabite"],
    ("Onesimus", "PC"): ["Colossae Church"],
    ("Onesiphorus", "PC"): ["Ephesus Church", "Missionary"],
    ("Pauls Nephew", "PC"): ["Jerusalem Church"],
    ("Peace Offering", "IR"): ["Offering"],
    ("Persian Archers", "PoC"): ["Persian"],
    ("Persian Conquerors", "PoC"): ["Persian"],
    ("Persian Horsemen", "PoC"): ["Persian"],
    ("Persian Horses", "PoC"): ["Persian"],
    ("Pharaohs Gifts", "IR"): ["Pharaoh"],
    ("Pharaohs Throne Room", "IR"): ["Pharaoh"],
    ("Pharaohs Throne Room", "Pi"): ["Pharaoh"],
    ("Philemon", "PC"): ["Colossae Church"],
    ("Philip the Evangelist", "Ap"): ["Deacon"],
    ("Philip the Evangelist", "EC"): ["Deacon"],
    ("Phoebe", "EC"): ["Corinth Church"],
    ("Pillar of Salt", "FM"): ["Canaanite Site"],
    ("Pleading with Edom", "II"): ["Edomite"],
    ("Plot to Kill", "RJ"): ["Sadducee"],
    ("Pontius Pilate", "P"): ["Roman"],
    ("Praise from Prison", "EC"): ["Roman"],
    ("Prayer and Fasting", "EC"): ["Missionary"],
    ("Priestly Breastplate", "Pi"): ["High Priest"],
    ("Prince of Persia", "Di"): ["Persian"],
    ("Priscilla", "EC"): ["Missionary"],
    ("Prison", "EC"): ["Sadducee"],
    ("Prochorus", "EC"): ["Deacon"],
    ("Questioning Christ", "Di"): ["Sadducee"],
    ("Quirinius", "J"): ["Roman"],
    ("Ram with Two Horns", "Di"): ["Persian"],
    ("Rash Oath", "TP"): ["Herod"],
    ("Refusal of Entry", "II"): ["Moabite"],
    ("Refused to Listen", "II"): ["Edomite"],
    ("Revolt", "PC"): ["Roman"],
    ("Rezon Son of Eliada", "LC"): ["Syrian"],
    ("Rhoda", "EC"): ["Jerusalem Church"],
    ("Ridicule", "GC"): ["Herod"],
    ("Roman Centurion", "GC"): ["Roman"],
    ("Roman Citizenship", "PC"): ["Roman"],
    ("Roman Horses", "RR"): ["Roman"],
    ("Roman Prison", "Pi"): ["Roman", "Roman Emperor", "Roman Soldier"],
    ("Romans Destroy Jerusalem", "LR"): ["Roman"],
    ("Romans Destroy Jerusalem", "RA"): ["Roman"],
    ("Sadducees", "Ap"): ["Sadducee"],
    ("Sadducees", "G"): ["Sadducee"],
    ("Sadducees", "LR"): ["Sadducee"],
    ("Salome", "TP"): ["Herod"],
    ("Samaria", "PoC"): ["King of Israel"],
    ("Sanhedrin", "Ap"): ["Sadducee"],
    ("Sanhedrin", "EC"): ["Sadducee"],
    ("Scapegoat", "Pi"): ["High Priest", "Offering"],
    ("Scapegoat", "PoC"): ["Offering"],
    ("Scribe", "Di"): ["Sadducee"],
    ("Secundus", "EC"): ["Missionary"],
    ("Seize Him!", "RJ"): ["Sadducee"],
    ("Selfish Possessions", "II"): ["Edomite"],
    ("Shobach", "P"): ["Syrian"],
    ("Shobach the Commander", "RR"): ["Syrian"],
    ("Sin Offering", "IR"): ["Offering"],
    ("Sin Offering", "Pi"): ["Offering"],
    ("Slaves to Eglon", "II"): ["Moabite"],
    ("Soldiers of Zobah", "CW"): ["Syrian"],
    ("Solomons Oppression", "LC"): ["King or Queen of Judah"],
    ("Solomons Temple", "P"): ["Temple Artifact"],
    ("Solomons Temple", "Pa"): ["Temple Artifact"],
    ("Solomons Temple", "RA3"): ["King or Queen of Judah", "Temple Artifact"],
    ("Sons of Ariel", "II"): ["Moabite"],
    ("Sowing Bountifully", "EC"): ["Corinth Church"],
    ("Stand Firm", "EC"): ["Thessalonica Church"],
    ("Stephanas", "EC"): ["Corinth Church"],
    ("Stoning of Stephen", "EC"): ["Sadducee"],
    ("Stormy Seas", "PC"): ["Roman"],
    ("Strong Force", "RA"): ["Syrian"],
    ("Strong Force", "RR"): ["Syrian"],
    ("Subdued Moabites", "II"): ["Moabite"],
    ("Summoned Curse", "II"): ["Moabite"],
    ("Supercilious Scribes", "GC"): ["Sadducee"],
    ("Syntyche", "PC"): ["Philippi Church"],
    ("Syrian Archer", "Ki"): ["Syrian"],
    ("Syrian Archer", "LR"): ["Syrian"],
    ("Syrian Mercenaries", "CW"): ["Syrian"],
    ("Syrian Reinforcements", "CW"): ["Syrian"],
    ("Syrian Victory", "Ki"): ["Syrian"],
    ("Taking Naboths Vineyard", "FF"): ["King of Israel"],
    ("Temple Dedication", "RA3"): ["Temple Artifact"],
    ("Temple Priests", "RA3"): ["Temple Artifact"],
    ("Temple Priests", "RR"): ["Temple Artifact"],
    ("Tenants Kill the Son", "Di"): ["Sadducee"],
    ("Terrifying Beast", "PoC"): ["Roman"],
    ("Terrifying Beast", "RA"): ["Roman"],
    ("Timon", "EC"): ["Deacon"],
    ("Timothy", "EC"): ["Missionary"],
    ("Titus Justus", "EC"): ["Corinth Church", "Missionary"],
    ("Untouchable", "GC"): ["Sadducee"],
    ("Uproar in Jerusalem", "PC"): ["Roman"],
    ("Urim and Thummim", "LR"): ["High Priest"],
    ("Urim and Thummim", "Pi"): ["High Priest"],
    ("Valiant Moabites", "II"): ["Moabite"],
    ("Vine-Growers Rebellion", "GC"): ["Sadducee"],
    ("Widows Tables", "EC"): ["Deacon"],
    ("Winged Leopard", "PoC"): ["Persian"],
    ("Winged Leopard", "RA"): ["Persian"],
    ("Wisdom", "PC"): ["Ephesus Church"],
    ("Word Spreads", "H"): ["Deacon"],
    ("Work with Your Hands", "EC"): ["Thessalonica Church"],
    ("Worship of Edom", "LC"): ["Edomite"],
    ("You Shall Not Pass!", "II"): ["Edomite"],
    ("Zephaniah", "PoC"): ["King or Queen of Judah"],
    ("Zeresh Advises Haman", "RA"): ["Persian"],
    ("Zerubbabels Temple", "FF"): ["Temple Artifact"],
    ("Zerubbabels Temple", "LC"): ["Feast", "Offering"],
}
