ORDIR_REFERENCE_MAP = {
    "Assyrian": [": Angel at Jerusalem", "Jonah", "King Hezekiah", "Nahum", "•"],
    "Babylonian": ["Habakkuk", "the Vindicator", "•"],
    "Bows, Arrows, Spears, Javelins and Darts": [": Shield of Faith", "•"],
    "Cloud Card": [": Abel", "Amram & Jochebed", "Cloud of Witnesses", "•"],
    "Deacon": [": Nicanor", "Philip the Evangelist", "Prochorus", "•"],
    "Depicting Morg": ["Evil Arises", "Gathering of Demons", "•", "•    Blade of Death"],
    "Disease": [": Brass Serpent", "Glad Tidings", "Miracle of Healing", "•"],
    "Egyptian": [": Death of Firstborn", "Jochebed", "and Journey to Egypt", "•"],
    "Ephesians 6 Enhancement": [": Saint of Virtue", "•"],
    "Fool": [": Ambushed Moabites", "Conspiring Herodians", "•"],
    "Genesis 1-7 Enhancement": [": Adam", "•"],
    "Genesis 12-24 Hero": [": Abraham", "•"],
    "Genesis 21-35 Enhancement": [": Isaac", "•"],
    "Gideon in the Title": [": Gideon", "•"],
    "Heretic": [": Archippus", "Barnabas", "Philemon", "Stand Firm", "•"],
    "Herod in the Title": [": Herodian", "•"],
    "II Chronicles 17-20 Hero": [": King Jehoshaphat", "•"],
    "II Chronicles 29-32 Hero": [": King Hezekiah", "•"],
    "Isaiah 6 Enhancement": [": Seraph with a Live Coal", "•"],
    "Lion": [": Coliseum Lion", "Hungry Lion", "Negev Lions", "•"],
    "Magician": [": Burning of Magic Books", "Philip the Evangelist", "•"],
    "Missionary": [": Aquila", "Bereans", "Burning of Magic Books", "•"],
    "Mob": [": Doomed Conspirators", "•"],
    "Paul in the Title": [": Epaphroditus", "•"],
    "Persian": [": Haggai", "and Malachi", "•"],
    "Prophet": [": Angel in the Path", "Anna", "Baptism of Jesus", "•"],
    "Samaritan": [": Citizens of Sychar", "Kindness", "Meeting the Messiah", "•"],
    "Scholar or Philosopher in the Title": [": Worldly Wisdom", "•"],
    "Star Card": ["Fountain of Living Water", "the Exile", "•"],
    "Syrian": [": Captain of the Chariots", "House of Rimmon", "King Asnappar", "•"],
    "Temple Artifact": [": Destruction of Nehushtan", "Filling Zerubbabel's Temple", "•"],
    "Temple Priest": ["His Name is John", "the Rebuilder", "•"],
    "Zechariah Card": [": Zerubbabel's Temple", "•"],
}
