ORDIR_FORWARD_MAP = {
    "Acts 12 Card": [": Angel of Deliverance", "Angel of the Lord", "•"],
    "Acts 19 Card": [": Burning of Magic Books", "•"],
    "Acts Card": [": Agabus", ": Angel of the Lord", ": Angelic Visit", "Ananias of Damascus", "Antidote", "Bless the Nations", "Blinding Light", "•"],
    "Animal": [": Bear", "Beasts of the Earth", "Behemoth", "Coliseum Lion", "•"],
    "Antediluvian": ["", ": Abel", "Adam", "the Exile", "•"],
    "Armor of God Enhancement": [": Belt of Truth", "Breastplate of Righteousness", "•"],
    "Assyrian": [": Ninevites", "and The King of Nineveh", "•"],
    "Assyrian Site": ["Halah", "and Nineveh", "•    Assyria"],
    "Babylonian": [": Nebuchadnezzar", "•"],
    "Babylonian Site": ["and Babylonian Banquet Hall", "•    Babylon"],
    "Based on Prophecy": [": Book of Nathan", "and Prophecy of Eldad & Medad", "•"],
    "Beast": [": Bear", "Beast from the Earth", "Beast from the Sea", "•"],
    "Bows, Arrows, Spears, Javelins and Darts": [": Abishai's Spear", "Adino's Spear", "•"],
    "Canaanite": [": Ahimelek the Hittite", "Ishmaiah the Gibeonite", "•"],
    "Canaanite Site": ["Hebron", "Hormah", "Jericho", "Pit of Dothan", "•    Canaan"],
    "Cloud Card": ["", ": Abed-nego", "Abel", "Abraham", "•"],
    "Connected with Demons": [": Mary Magdalene", "•"],
    "Daniel Card": ["", ": Abed-nego", ": Daniel's Prayer", ": Son of God", "Abednego", "Daniel", "Faith Unbowed", "Michael's Sword", "•"],
    "Deacon": [": Nicanor", "Nicolas of Antioch", "Parmenas", "•"],
    "Demon": [": Abaddon the Destroyer", "Admiral", "Afflicting Spirit", "•"],
    "Depicting a Weapon": [": Book of the Wars", "and Shield of Faith", "•"],
    "Deuteronomy Card": [": Balaam", ": Blessings for Obedience", ": Doubt", "Courage", "Doomed Canaanites", "Doubt", "Emim", "and Israel's Rebellion", "•"],
    "Disciple": ["First Called", "Fisher of Men", "•    Andrew"],
    "Disease": [": Eaten by Worms", "and Sowing the Seed", "•"],
    "Edomite": [": Basemath", "Charioteers of Seir", "David's Servants", "•"],
    "Egyptian Site": ["Egypt", "Pharaoh's Court", "•    Banks of the Nile"],
    "Empty Tomb Hero": ["Angel at Tomb", "Joanna", "•    Angel at the Tomb"],
    "Ephesians Card": [": Belt of Truth", ": Lost Soul [Ephesians 5:14]", ": Music Leader", "Breastplate of Righteousness", "and Soldier of God", "•"],
    "Esther Card": ["", ": Courage of Esther", ": Esther", ": Haman's Gallows", "Hadassah", "and Haman's Plot Exposed", "the Courageous", "•"],
    "Exodus Card": [": Aaron", ": Aaron's Rod", "Antidote", "Burning Bush", "God's Mediator", "•"],
    "Ezekiel Card": [": Baggage", ": Cherubim", ": Valley of Dry Bones", "Charred Vine", "Drawn Sword", "Ezekiel", "•"],
    "Ezra Card": [""Accusers"]", ": Cymbals of the Levites", ": Ezra", "Ezra's Journey", "Favored by God", "the Restorer", "•"],
    "Feast": [": Day of Atonement", "Feast of Atonement", "Feast of Booths", "•"],
    "Flood Survivor": [": Ham", "Ham's Wife", "Japheth", "Japheth's Wife", "•"],
    "Fool": [": Ambushed Moabites", "Conspiring Herodians", "•"],
    "Fruit of the Spirit": [": Faithfulness", "Gentleness", "Goodness", "Joy", "•"],
    "Gender": [": Boaz' Reapers", "Bride of Christ", "Citizens of Sychar", "•"],
    "Generic Character": ["Abusive Soldiers", "Abusive Taskmaster", "Angel at Bethesda", "Angel at Jerusalem", "Captive Princes", "Man with Withered Hand", "•    Abram's Army", "•    Absalom's Soldiers", "•    Blood Avenger"],
    "Genesis 1-7 Enhancement": [": Abel's Sacrifice", "Construction Begins", "Covenant of Eden", "•"],
    "Genesis 12-24 Hero": [": Abraham", "Abram", "the Blameless", "•"],
    "Genesis 3 Curse": ["Cursed Ground", "Serpent's Curse", "•    Birthing Pains"],
    "Genesis 37-50 Card": [": Asher", ": Brother's Reunion", ": Out of Their Hands", "Benjamin", "Brought to Egypt", "Buying Grain", "the Rich", "the Young", "•"],
    "Genesis Card": [": A New Beginning", ": Abel", "A Wife for Isaac", "Abel's Sacrifice", "Abraham", "Abram", "and Out of Their Hands", "the Blameless", "•"],
    "Giant": ["Emim", "Greatest Anakim", "Son of Anak", "•"],
    "Giant Slayer": [": Abishai", "Caleb", "Chief of Thirty", "•"],
    "Greek": [": Nicolas of Antioch", "Titus", "the Messenger", "•"],
    "Haggai Card": [": Haggai", "•"],
    "Heavenly Temple Artifact": ["The Book of Life", "The Golden Altar", "•    Ark of the Covenant"],
    "Hebrews Card": [": Dutiful Priest", ": Entertaining Angels", ": The Second Coming", "Equipped for the Mission", "The Angel of the Winds", "•"],
    "Herod": [": Archelaus", "Herod Agrippa I", "Herod Archelaus", "•"],
    "Herod in the Title": ["Altar of Incense", "Golden Cherubim", "•    Altar of Burnt Offering"],
    "High Priest": [": Aaron", "God's Mediator", "•"],
    "House of Eleazar": [": Ahimaaz", "Amariah the High Priest", "the Swift", "•"],
    "House of Ithamar": [": Abiathar", "Chief Priest", "the Survivor", "•"],
    "I Chronicles Card": [": Abiezer", ": Book of Gad the Seer", ": Musicians' Chambers", "Abishai", "Amasai the Raider", "Asaph", "Book of Nathan", "Bronze Cymbals", "and Stronghold in the Desert", "•"],
    "I Samuel Card": [": Abiathar", ": Called to Prophesy", "Abigail", "and Lord of Armies", "the Survivor", "•"],
    "I Thessalonians Card": [": In the Clouds", ": Letters to the Thessalonians", "and Work with Your Hands", "•"],
    "II Chronicles 17-20 Hero": [": Amariah the High Priest", "the High Priest", "•"],
    "II Chronicles 26 Enhancement": [": Acts of Uzziah", "Body Armor", "Break Down the Wall of Gath", "•"],
    "II Chronicles 29-32 Hero": [": Angel at Jerusalem", "and Azariah the High Priest", "•"],
    "II Chronicles Card": [": Acts of Uzziah", ": Glory of the Lord", "Amariah the High Priest", "Appointing Judges", "Body Armor", "the Conqueror", "•"],
    "II Kings Card": [": Chariot of Fire", "Elisha", "the Just", "the Strong", "•"],
    "II Samuel 14-17 Evil Character": [": Ahimaaz", "Hushai", "Ittai", "Tekoan Woman", "•"],
    "II Samuel 14-18 Evil Character": [": Ahimaaz", "Hushai", "Ittai", "the Swift", "•"],
    "II Samuel Card": [""Banished"]", ": Abishai's Spear", "Adino", "Adino's Spear", "Chief of Thirty", "the Anathothite", "•"],
    "II Thessalonians Card": [": Might of Angels", "and Stand Firm", "•"],
    "Idol": [": Altar of Dagon", "Asherah Pole", "Gideon's Ephod", "•"],
    "Isaiah 6 Enhancement": [": Forcefulness of Isaiah", "Isaiah's Call", "and Live Coal", "•"],
    "Isaiah Card": [": Angel of His Presence", ": Bearing Our Sin", "By His Wounds", "Confused", "Covenant Keepers", "Isaiah", "•"],
    "James Card": [""Demon Shuffle"]", ": Endurance of Job", ": James", "Leader in Jerusalem", "and Mercy of James", "•"],
    "Jeremiah Card": [": Balm of Gilead", ": Buckler", ": Jeremiah", "Battle Axe", "Hope Bringer", "•"],
    "Job Card": [""Vindicated"]", ": Behemoth", ": Job", "Day of Fury", "Endurance of Job", "the Perseverant", "•"],
    "John Card": [": A New Commandment", "Behold the Lamb", "Bread of Life", "First Called", "Fisher of Men", "•"],
    "Jonah Card": [": Chastisement of the Lord", ": Jonah", ": Nineveh", "God's Mercy", "•"],
    "Joshua Card": [": Ambush", ": Caleb", ": The Long Day", "Ambush the City", "Army of the Lord", "the Rewarded", "•"],
    "Judge": [": Abdon", "Deborah", "the Brave", "•"],
    "Judges Card": [": Abdon", ": Forced Labor", "Angel with the Secret Name", "Army of Simeonites", "•"],
    "King": ["the Blameless", "the Conqueror", "the Just", "•"],
    "King of Israel": [": David [Green]", "David [Red]", "Giant Slayer", "•"],
    "King or Queen of Judah": [": Abigail", "the Conqueror", "the Just", "•"],
    "Lamentations Card": [": Cup of Wrath", "Desolate Gateways", "Hunger", "Lamenting", "•"],
    "Leviticus Card": [": Burnt Offering", ": I Am Holy", "Day of Atonement", "Feast of Booths", "Peacemaker", "son of Aaron", "•"],
    "Lion": [": Coliseum Lion", "Devouring Lion", "Hungry Lion", "Lions", "•"],
    "Luke Card": [": A Child is Born", ": Andrew", ": Angel of the Lord", "Amazing Faith", "An Angel Appears", "Anna", "the Widow", "•"],
    "Major or Minor Prophet": ["", ": Daniel", "Daniel", "•"],
    "Mark Card": [": Bartimaeus", ": Boanerges", ": Lost Soul [Mark 1:40]", "Faith of Bartimaeus", "Jairus", "Jairus' Daughter", "Love of Jesus", "•"],
    "Martyr": ["First Called", "Fisher of Men", "•    Andrew"],
    "Matthew Card": [": A Roman Soldier's Faith", ": The Resurrection", "Alabaster Jar", "Angelic Guidance", "Star of Bethlehem", "the Exilarch", "the Progeny", "•"],
    "Micah Card": [": Bethlehem", ": Micah", ": Out of Bethlehem", "Swords into Plowshares", "•"],
    "Moabite": [": Ruth", "the Devoted", "the Redeemed", "•"],
    "Musician": ["Barak", "Chenaniah", "the Psalmist", "•    Asaph"],
    "Nativity Card": [": A Child is Born", ": Angel of Warning", ": Angel of the Lord", "An Angel Appears", "Angelic Guidance", "Anna", "Son of God", "the Widow", "•"],
    "Nehemiah Card": [": Builder's Spear", ": Rubble and Dust", "Builder's Sword", "Determination of Nehemiah", "Eliashib the High Priest", "Son of Zabbai", "•"],
    "Numbers Card": [": Angel in the Path", ": Angel's Sword", ": Forty Years", "Book of the Wars", "Brass Serpent", "Dreamers", "Eldad", "•"],
    "Patriarch": [": Abram", "Abraham", "Asher", "the Blameless", "•"],
    "Persian": ["", ": Esther", "and Hadassah", "the Courageous", "•"],
    "Persian Site": ["and Lions' Den", "•    Lion's Den"],
    "Pharaoh": [": King Shishak", "King So", "Pharaoh", "Pharaoh Hophra", "•"],
    "Philistine": [": Ittai", "and Obed-Edom the Gittite", "•"],
    "Plague": [": Death of Firstborn", "Plague of Blood", "•"],
    "Poison": [": Bad Figs", "Fiery Serpents", "Poison", "•"],
    "Postexilic": ["the Exilarch", "the Progeny", "•"],
    "Priest": [": Aaron", "God's Mediator", "•"],
    "Priestly Artifact": ["Priestly Breastplate", "Priestly Crown", "•    Blue Tassels"],
    "Prophet": ["Caiaphas the Conspirator", "God's Mediator", "Moses' Brother", "Son of Beor", "•    Aaron", "•    Balaam"],
    "Revelation 12-19 Evil Character": [": Babylon the Great", "Beast from the Earth", "•"],
    "Revelation Angel": [": Angel from the Altar", "Angel from the Sun", "Angel of Might", "•"],
    "Revelation Card": [": A Mighty Blow", ": Angel from the Altar", ": Grapes of Wrath", "Angel from the Sun", "Angel of Might", "Blood of the Lamb", "•"],
    "Roman": [": Aquila", "Centurion", "Claudia", "•"],
    "Roman Centurion": [": Centurion", "Cornelius", "The Centurion at Calvary", "•"],
    "Roman Emperor": [": Emperor Augustus", "Emperor Caius Caligula", "•"],
    "Roman Governor": [": Antonius Felix", "Governor Felix", "Pontius Pilate", "•"],
    "Roman Site or Fortress": [": Nero's Realm", "and Roman Prison", "•"],
    "Roman Soldier": [": Centurion", "Cornelius", "The Centurion at Calvary", "•"],
    "Royalty (or Royal or Member of a Royal Family)": [": Abigail", "the Conqueror", "the Just", "•"],
    "Ruth Card": [": Abeyance", ": Boaz' Sandal", "Best Friends", "Boaz", "Boaz' Offspring", "Boaz' Resolve", "the Generous", "the Gracious", "•"],
    "Samaritan": [": Citizens of Sychar", "Good Samaritan", "The Good Samaritan", "•"],
    "Scholar or Philosopher in the Title": [": Amariah the High Priest", "the High Priest", "•"],
    "Son of Jacob": [": Asher", "Benjamin", "the Rich", "the Young", "•"],
    "Spiritual Gifts": [": Spiritual Gifts", "•"],
    "Star Card": [": A Royal Priesthood", ": Star of Bethlehem", "Abraham's Descendant", "Amazing Faith", "God's Mediator", "the Progeny", "•"],
    "Syrian": [": Leah", "God's Choice", "Weary-Eyed", "•"],
    "Tabernacle Artifact": ["Altar of Burnt Offering", "Altar of Incense", "•    Aaron's Staff"],
    "Tabernacle Priest": [": Aaron", "God's Mediator", "•"],
    "Temple Artifact": ["Altar of Burnt Offering", "Altar of Incense", "•    Aaron's Staff"],
    "Temple Priest": [": Amariah the High Priest", "the High Priest", "•"],
    "Thief": ["Barabbas", "Concealed Canaanites", "•    Ambushing Bandits"],
    "Wilderness Character": [": Aaron", "God's Mediator", "•"],
    "Zechariah Card": [": A Royal Priesthood", ": Eliashib the High Priest", ": Joshua the High Priest", ": The Flying Scroll", "Altar of Incense", "Bow of Battle", "By My Spirit", "Ezra", "Favored by God", "Messenger Angel", "Mighty Men", "•", "•    Altar of Burnt Offering"],
}
