ORDIR_REFERENCE_CARD_MAP = {
    "Assyrian": ["Angel at Jerusalem", "Jonah", "King Hezekiah", "Nahum"],
    "Babylonian": ["Ezekiel", "Habakkuk", "Seraiah the High Priest", "the Vindicator"],
    "Bows, Arrows, Spears, Javelins and Darts": ["Shield of Faith"],
    "Cloud Card": ["Abel", "Amram & Jochebed", "Cloud of Witnesses", "Daniel"],
    "Deacon": ["EC)", "Nicanor", "Philip the Evangelist (Ap", "Prochorus", "The Ethiopian"],
    "Depicting Morg": ["Evil Arises", "Gathering of Demons", "Intent to Kill", "Morg AW", "•    Blade of Death"],
    "Disease": ["Brass Serpent", "Glad Tidings", "Miracle of Healing", "Peter's"],
    "Egyptian": ["Alexandrian Ship", "Captain Potiphar", "Cupbearer's Complaints", "Death of Firstborn", "Jochebed", "Journey to Egypt"],
    "Ephesians 6 Enhancement": ["Saint of Virtue"],
    "Fool": ["Ambushed Moabites", "Conspiring Herodians", "Conspiring Servants"],
    "Genesis 1-7 Enhancement": ["Adam"],
    "Genesis 12-24 Hero": ["Abraham"],
    "Genesis 21-35 Enhancement": ["Isaac"],
    "Gideon in the Title": ["Gideon"],
    "Heretic": ["Archippus", "Barnabas", "Philemon", "Stand Firm", "The"],
    "Herod in the Title": ["Herodian"],
    "II Chronicles 17-20 Hero": ["King Jehoshaphat"],
    "II Chronicles 29-32 Hero": ["King Hezekiah"],
    "Isaiah 6 Enhancement": ["Seraph with a Live Coal"],
    "Lion": ["Coliseum Lion", "Hungry Lion", "Negev Lions", "Pride of Lions"],
    "Magician": ["Burning of Magic Books (Ap", "EC)", "Philip the Evangelist", "Tested by Fire"],
    "Missionary": ["Aquila", "Bereans", "Burning of Magic Books", "Epaphroditus"],
    "Mob": ["Doomed Conspirators"],
    "Paul in the Title": ["Epaphroditus (Ap", "PC)"],
    "Persian": ["Haggai", "Haman", "Haman's Boasting", "Haman's Gallows", "Honor Thy", "Malachi"],
    "Prophet": ["Angel in the Path", "Anna", "Baptism of Jesus", "Bearing Our Sin"],
    "Samaritan": ["Citizens of Sychar", "Kindness", "Meeting the Messiah", "The"],
    "Scholar or Philosopher in the Title": ["Worldly Wisdom"],
    "Star Card": ["'I AM' Has Sent Me", "Adam", "Fountain of Living Water", "the Exile"],
    "Syrian": ["Captain of the Chariots", "House of Rimmon", "King Asnappar"],
    "Temple Artifact": ["Destruction of Nehushtan", "Filling Zerubbabel's Temple", "Glory of"],
    "Temple Priest": ["Hilkiah", "His Name is John", "Zechariah", "the", "the Rebuilder"],
    "Zechariah Card": ["LC)", "Zerubbabel's Temple (FF"],
}
