SET_ALIAS = {
    "10A": ["G", "H"],
    "1E": ["A", "B"],
    "1EU": ["A", "B", "B-Ul"],
    "2E": ["C", "D"],
    "2ER": ["C", "D", "C-2nd"],
    "3E": ["E", "F"],
    "AU": "A",
    "AW": "AW",
    "Ap": "Ap",
    "CoW": ["CW", "CW-Main"],
    "CoW (AB)": ["CW", "CW-Alt", "CW-Main"],
    "CoW [Ban]": "CW",
    # neu: Kürzel, die nur im Namen vorkommen
    "CL": "Or",   # Faithful Servant (CL)
    "Di": "Di",
    "DU": "D",
    "FoM": "FM",
    "FoOF": ["FF", "FF2"],
    "FooF": ["FF", "FF2"],
    "Fund": "P",
    "GoC": "GC",
    "I": "I",
    "I/J+": "IJ+",
    "II": "II",
    "IR": "IR",
    "J": "J",
    "K": "K",
    "K1P": "K",
    "Ki": "Ki",
    "L": "L",
    "L1P": "L",
    "LoC": "LC",
    "Main": ["Or"],
    "Main UL": ["Or"],
    "Main UL [Ban]": ["Or"],
    "Main [Ban]": ["Or"],
    "Pat": "Pa",
    "Pmo-P1": ["P", "P-Settlers", "P-District", "P-2019"],
    "Pmo-P2": ["P", "P-2009", "P-2016", "P-2017", "P-2018", "P-2019", "P-2019 Seasonal", "P-2019 Winner", "P-2019 Nationals", "P-2020", "P-2022 Seasonal", "P-2023", "P-2023 Baptism", "P-2023 Greek", "P-2023 Hebrew", "P-2023 Nationals", "P-2024"],
    "Pmo-P3": "P",
    "PoC": "PoC",
    "PoC [Ban]": "PoC",
    "Pri": "Pi",
    "Prp": "Pr",
    "RR": "RR",
    "RoA": ["RA", "RA2", "RA3"],
    "RoA 3": ["RA", "RA2", "RA3"],
    "RoA [Ban]": ["RA", "RA2", "RA3"],
    "RoJ": "RJ",
    "RoJ (AB)": "RJ",
    "TEC": "EC",
    "TPC": "PC",
    "TPC [Ban]": "PC",
    "TxP": "TP",
    "War": "Wa",
    "Wom": "Wo"
}
