from typing import Literal

OrdirCategory = Literal[
    "Acts Card",
    "Acts 12 Card",
    "Acts 19 Card",
    "Angel",
    "Animal",
    "Antediluvian",
    "Armor of God Enhancement",
    "Assyrian",
    "Assyrian Site",
    "Babylonian",
    "Babylonian Site",
    "Based on Prophecy",
    "Beast",
    "Berea Church",
    "Bows, Arrows, Spears, Javelins and Darts",
    "Caesarea Church",
    "Canaanite",
    "Canaanite Site",
    "Character’s Role and Gender",
    "Christ or Jesus in the Title or Scripture Verse",
    "Church",
    "Cloud Card",
    "Colossae Church",
    "Connected with David",
    "Connected with Demons",
    "Corinth Church",
    "Damascus Church",
    "Daniel Card",
    "David in the Title or Scripture Verse",
    "Deacon",
    "Demon",
    "Depicting a Weapon",
    "Depicting an Evil Altar",
    "Depicting an Idol",
    "Depicting Morg",
    "Deuteronomy Card",
    "Disciple",
    "Disease",
    "Duplicate Card",
    "Edomite",
    "Egyptian",
    "Egyptian Site",
    "Empty Tomb Hero",
    "Ephesians Card",
    "Ephesians 6 Enhancement",
    "Ephesus Church",
    "Esther Card",
    "Ethiopia Church",
    "Evil Altar",
    "Exodus Card",
    "Ezekiel Card",
    "Ezra Card",
    "False Religious Practice",
    "Feast",
    "Flood Survivor",
    "Fool",
    "Fought in an Earthly Battle",
    "Fruit of the Spirit",
    "Gender",
    "Generic Character",
    "Genesis Card",
    "Genesis 1-7 Enhancement",
    "Genesis 3 Curse",
    "Genesis 6 Enhancement",
    "Genesis 6-10 Card",
    "Genesis 12-24 Hero",
    "Genesis 21-35 Enhancement",
    "Genesis 37-50 Card",
    "Giant",
    "Giant Slayer",
    "Gideon in the Title",
    "Gospel Card",
    "Greek",
    "Haggai Card",
    "Heavenly Temple Artifact",
    "Hebrews Card",
    "Heretic",
    "Herod",
    "Herod in the Title",
    "Herod’s Temple Artifact",
    "High Priest",
    "House of Eleazar",
    "House of Ithamar",
    "Human",
    "Idol",
    "Involves Music",
    "Isaiah Card",
    "Isaiah 6 Enhancement",
    "I Chronicles Card",
    "I Samuel Card",
    "I Thessalonians Card",
    "II Chronicles Card",
    "II Chronicles 17-20 Hero",
    "II Chronicles 26 Enhancement",
    "II Chronicles 29-32 Hero",
    "II Kings Card",
    "II Samuel Card",
    "II Samuel 14-17 Evil Character",
    "II Samuel 14-18 Evil Character",
    "II Thessalonians Card",
    "James Card",
    "Jeremiah Card",
    "Jerusalem Church",
    "Job Card",
    "John Card",
    "Jonah Card",
    "Joppa Church",
    "Joseph in the Title or Scripture Verse",
    "Joshua Card",
    "Judge",
    "Judges Card",
    "King",
    "King of Israel",
    "King or Queen of Judah",
    "Lamentations Card",
    "Leviticus Card",
    "Lion",
    "Luke Card",
    "Lystra Church",
    "Magician",
    "Major or Minor Prophet",
    "Mark Card",
    "Martyr",
    "Matthew Card",
    "Medo-Persian",
    "Mentioned in I or II Samuel",
    "Micah Card",
    "Missionary",
    "Moabite",
    "Mob",
    "Musician",
    "Nationality",
    "Nativity Card",
    "Nehemiah Card",
    "Non-human",
    "N.T.",
    "Numbers Card",
    "O.T.",
    "Offering",
    "Patriarch",
    "Paul in the Title",
    "Persian",
    "Persian Site",
    "Pharaoh",
    "Pharisee",
    "Philippi Church",
    "Philistine",
    "Philistine Site",
    "Plague",
    "Poison",
    "Postexilic",
    "Priest",
    "Priestly Artifact",
    "Prophet",
    "Revelation Angel",
    "Revelation Card",
    "Revelation 12-19 Evil Character",
    "Roman",
    "Roman Centurion",
    "Roman Emperor",
    "Roman Governor",
    "Roman Site or Fortress",
    "Roman Soldier",
    "Rome Church",
    "Royalty (or Royal or Member of a Royal Family)",
    "Ruth Card",
    "Sadducee",
    "Samaritan",
    "Scholar or Philosopher in the Title",
    "Solomon’s Temple Priest",
    "Son of Jacob",
    "Spiritual Gifts",
    "Star Card",
    "Symbolic Character",
    "Syrian",
    "Tabernacle Artifact",
    "Tabernacle Priest",
    "Temple Artifact",
    "Temple Priest",
    "Thessalonica Church",
    "Thief",
    "Wilderness Character",
    "Zechariah Card",
    "Zerubbabel’s Temple Artifact",
    "Zerubbabel’s Temple Priest"
]
